// Generated by Cypress Author on 2026-09-10 for IMP-00.05.
/* eslint @typescript-eslint/no-require-imports: "off" */
const { defineConfig } = require('cypress');
const { readFileSync, mkdirSync, writeFileSync } = require('node:fs');
const { resolve, join } = require('node:path');
const { identityTasks } = require('./tests/identity-fixture.cjs');
const { academicTasks } = require('./tests/academic-fixture.cjs');

const reportDirectory = resolve(__dirname, '.local/reports/imp-01');

module.exports = defineConfig({
  video: false,
  screenshotOnRunFailure: false,
  numTestsKeptInMemory: 0,
  retries: 0,
  viewportWidth: 1280,
  viewportHeight: 900,
  defaultCommandTimeout: 15_000,
  requestTimeout: 15_000,
  responseTimeout: 15_000,
  taskTimeout: 35_000,
  reporter: 'dot',
  e2e: {
    baseUrl: 'http://127.0.0.1:3100',
    specPattern: 'tests/e2e/*.cy.ts',
    supportFile: 'tests/e2e/support.ts',
    testIsolation: true,
    setupNodeEvents(on, config) {
      if (!process.env.ALUNZA_TEST_STATE) {
        throw new Error(
          'Ejecuta npm run test:e2e para preparar el entorno aislado.',
        );
      }
      let state;
      let controlUrl;
      try {
        state = JSON.parse(readFileSync(process.env.ALUNZA_TEST_STATE, 'utf8'));
        controlUrl = new URL(
          process.env.ALUNZA_E2E_CONTROL_URL || 'http://invalid',
        );
      } catch {
        throw new Error(
          'No se pudo cargar la configuración local aislada de Cypress.',
        );
      }
      const apiBaseUrl = process.env.ALUNZA_TEST_API_URL;
      const controlKey = process.env.ALUNZA_E2E_CONTROL_KEY;
      if (
        state.projectId !== 'alunza-edu-foundation-test' ||
        state.authUrl !== 'http://127.0.0.1:16421' ||
        apiBaseUrl !== 'http://127.0.0.1:4100' ||
        config.baseUrl !== 'http://127.0.0.1:3100' ||
        controlUrl.protocol !== 'http:' ||
        controlUrl.hostname !== '127.0.0.1' ||
        !controlUrl.port ||
        controlUrl.username ||
        controlUrl.password ||
        controlUrl.search ||
        controlUrl.hash ||
        controlUrl.pathname !== '/' ||
        typeof controlKey !== 'string' ||
        controlKey.length < 32 ||
        typeof state.fixturePassword !== 'string' ||
        !state.fixturePassword
      ) {
        throw new Error(
          'Cypress solo puede operar el proyecto local aislado de pruebas.',
        );
      }

      // Explicit allowlist: no administrative key, database URL or control key enters the browser.
      config.env = { fixturePassword: state.fixturePassword, apiBaseUrl };
      async function control(action) {
        try {
          const response = await fetch(new URL(`/api/${action}`, controlUrl), {
            method: 'POST',
            headers: { 'x-alunza-e2e-key': controlKey },
            signal: AbortSignal.timeout(30_000),
            redirect: 'error',
          });
          if (response.status !== 200 || (await response.json()).ok !== true)
            throw new Error();
          return null;
        } catch {
          throw new Error(
            `No se pudo completar el control local de API (${action}).`,
          );
        }
      }
      on('task', {
        ...identityTasks(state),
        ...academicTasks(state),
        'foundation:apiStop': () => control('stop'),
        'foundation:apiStart': () => control('start'),
      });

      on('after:run', (result) => {
        if (!result || !Array.isArray(result.runs)) return;
        const states = new Set(['passed', 'failed', 'pending', 'skipped']);
        const tests = result.runs.flatMap((run) =>
          (run.tests || []).map((test) => ({
            id:
              (test.title || [])
                .join(' ')
                .match(/\b(?:FND-\d{2}|IMP01-\d{2}|IMP02-\d{2})\b/)?.[0] ||
              'UNKNOWN',
            state: states.has(test.state) ? test.state : 'unknown',
          })),
        );
        const report = {
          schemaVersion: 1,
          increment: 'IMP-02',
          recordedAt: new Date().toISOString(),
          browser: /^[a-z]+$/i.test(result.browserName)
            ? result.browserName
            : 'unknown',
          browserVersion: /^[0-9.]+$/.test(result.browserVersion)
            ? result.browserVersion
            : 'unknown',
          cypressVersion: /^[0-9.]+$/.test(result.cypressVersion)
            ? result.cypressVersion
            : 'unknown',
          spec: 'tests/e2e/*.cy.ts',
          status:
            result.totalFailed > 0
              ? 'failed'
              : result.totalPassed > 0 &&
                  result.totalPending === 0 &&
                  result.totalSkipped === 0
                ? 'passed'
                : 'incomplete',
          total: result.totalTests,
          passed: result.totalPassed,
          failed: result.totalFailed,
          pending: result.totalPending,
          skipped: result.totalSkipped,
          durationMs: result.totalDuration,
          tests,
        };
        mkdirSync(reportDirectory, { recursive: true });
        writeFileSync(
          join(reportDirectory, 'e2e.json'),
          JSON.stringify(report, null, 2) + '\n',
        );
        const academicReports = resolve(__dirname, '.local/reports/imp-02');
        mkdirSync(academicReports, { recursive: true });
        writeFileSync(
          join(academicReports, 'e2e.json'),
          JSON.stringify(report, null, 2) + '\n',
        );
      });
      return config;
    },
  },
});
