// Generated by Cypress Author on 2026-09-23 for IMP-02.
import type { Session } from '@supabase/supabase-js';
import type {
  Activity,
  AcademicClass,
  Concept,
  Course,
  Exercise,
  JoinCode,
} from '@alunza/contracts';
import identityFixture from '../../fixtures/foundation/identity.json';

const organizationId = identityFixture.organizations[0]!.id;
const teacherId = identityFixture.users.find(
  (user) => user.organizationId === organizationId && user.role === 'TEACHER',
)!.id;
const draftPrefix = 'alunza.exercise-draft.v1:';
const limits = { memoryBytes: 134217728, runtimeMs: 3000, outputBytes: 65536 };
type Setup = {
  admin: Session;
  teacher: Session;
  student: Session;
  course: Course;
  classroom: AcademicClass;
  concept: Concept;
  exercise: Exercise;
  activity: Activity;
  joinCode: JoinCode;
};

function rest<T extends object>(
  session: Session,
  method: 'GET' | 'POST' | 'PATCH' | 'PUT',
  path: string,
  body?: Record<string, unknown>,
  revision?: number,
): Cypress.Chainable<T> {
  return cy
    .env(['apiBaseUrl'], { log: false })
    .then(({ apiBaseUrl }) =>
      cy.request<{ data: T }>({
        method,
        url: `${apiBaseUrl}/api/v1${path}`,
        body,
        log: false,
        headers: {
          Authorization: `Bearer ${session.access_token}`,
          'Idempotency-Key': crypto.randomUUID(),
          ...(revision ? { 'If-Match': `"${revision}"` } : {}),
        },
      }),
    )
    .then((response) => {
      expect(response.status).to.be.within(200, 299);
      return cy.wrap(response.body.data, { log: false });
    });
}

function visitAs(
  session: Session,
  path: string,
  beforeLoad?: (window: Cypress.AUTWindow) => void,
) {
  return cy.visit(path, {
    onBeforeLoad(window) {
      window.localStorage.setItem(
        'alunza.auth.127.0.0.1:18421',
        JSON.stringify(session),
      );
      beforeLoad?.(window);
    },
  });
}

function setup(published = true): Cypress.Chainable<Setup> {
  const suffix = crypto.randomUUID().slice(0, 8);
  return cy
    .task<Session>('identity:login', 'ADMIN', { log: false })
    .then((admin) =>
      cy
        .task<Session>('identity:login', 'TEACHER', { log: false })
        .then((teacher) =>
          cy
            .task<Session>('identity:login', 'STUDENT', { log: false })
            .then((student) =>
              rest<Course>(
                admin,
                'POST',
                `/organizations/${organizationId}/courses`,
                {
                  code: `CUR-${suffix}`,
                  name: `Curso E2E ${suffix}`,
                  description: 'Curso ficticio de aceptación',
                  academicPeriod: '2026-2',
                  startDate: '2026-08-01',
                  endDate: '2026-12-31',
                },
              ).then((course) =>
                rest<Course>(
                  admin,
                  'PUT',
                  `/courses/${course.id}/teachers/${teacherId}`,
                  { enabled: true },
                  course.revision,
                ).then(() =>
                  rest<Concept>(
                    admin,
                    'POST',
                    `/organizations/${organizationId}/concepts`,
                    {
                      name: `Concepto E2E ${suffix}`,
                      description: 'Operaciones numéricas',
                      parentId: null,
                    },
                  ).then((concept) =>
                    rest<AcademicClass>(
                      teacher,
                      'POST',
                      `/organizations/${organizationId}/classes`,
                      {
                        courseId: course.id,
                        code: `CLS-${suffix}`,
                        name: `Clase E2E ${suffix}`,
                        description: 'Clase ficticia',
                        startDate: '2026-08-01',
                        endDate: '2026-12-31',
                      },
                    ).then((classroom) => {
                      const definition = {
                        title: `Sumar ${suffix}`,
                        statement: 'Devuelve la suma de los dos argumentos.',
                        starterCode:
                          'module.exports.solve = function solve(a, b) {\n  return 0;\n};',
                        language: 'javascript',
                        entrypoint: 'solve',
                        difficulty: 'BEGINNER',
                        conceptVersionIds: [concept.currentVersionId],
                        tests: [
                          {
                            id: 'visible-suma',
                            visibility: 'visible',
                            args: [2, 3],
                            expected: 5,
                          },
                          {
                            id: 'hidden-sentinel-e2e',
                            visibility: 'hidden',
                            args: [98761, 34529],
                            expected: 133290,
                          },
                        ],
                        executionLimits: limits,
                      };
                      return rest<Exercise>(
                        teacher,
                        'POST',
                        `/organizations/${organizationId}/exercises`,
                        definition,
                      ).then((exercise) =>
                        rest<Exercise>(
                          teacher,
                          'POST',
                          `/organizations/${organizationId}/exercises`,
                          { ...definition, title: `Segunda suma ${suffix}` },
                        ).then((second) =>
                          rest<Activity>(
                            teacher,
                            'POST',
                            `/classes/${classroom.id}/activities`,
                            {
                              title: `Actividad E2E ${suffix}`,
                              instructions:
                                'Lee el enunciado y prepara tu solución.',
                              type: 'FORMATIVE',
                              opensAt: null,
                              closesAt: null,
                              exercises: [
                                {
                                  exerciseVersionId: exercise.currentVersionId,
                                  position: 0,
                                  required: true,
                                },
                                {
                                  exerciseVersionId: second.currentVersionId,
                                  position: 1,
                                  required: true,
                                },
                              ],
                            },
                          ).then((draft) => {
                            const activityRequest = published
                              ? rest<Activity>(
                                  teacher,
                                  'POST',
                                  `/activities/${draft.id}/publish`,
                                  {},
                                  draft.revision,
                                )
                              : cy.wrap(draft, { log: false });
                            return activityRequest.then((activity) =>
                              rest<JoinCode>(
                                teacher,
                                'POST',
                                `/classes/${classroom.id}/join-codes`,
                                {},
                                classroom.revision,
                              ).then((joinCode) => ({
                                admin,
                                teacher,
                                student,
                                course,
                                classroom,
                                concept,
                                exercise,
                                activity,
                                joinCode,
                              })),
                            );
                          }),
                        ),
                      );
                    }),
                  ),
                ),
              ),
            ),
        ),
    );
}

function enroll(context: Setup) {
  return rest(context.student, 'POST', '/class-enrollments', {
    code: context.joinCode.code,
  });
}
function dialog() {
  return cy.get('[role="dialog"]').should('be.visible');
}
function editorPath(context: Setup) {
  return `/actividades/${context.activity.id}/ejercicios/${context.activity.exercises[0]!.id}`;
}

describe('IMP-02 · Contenido y editor con servicios reales', () => {
  it('IMP02-01 · Administrador configura un curso y conceptos → recupera cambios y rechaza duplicados sin perder campos', () => {
    setup().then((context) => {
      visitAs(context.admin, `/academia?org=${organizationId}`);
      cy.contains('[data-cy="course-card"]', context.course.code).within(() =>
        cy.contains('button', 'Editar curso').click(),
      );
      dialog().within(() => {
        cy.get('[name="name"]')
          .clear()
          .type('Curso actualizado desde interfaz');
        cy.contains('button', /^Guardar$/).click();
      });
      cy.get('[role="dialog"]').should('not.exist');
      cy.reload();
      cy.contains('[data-cy="course-card"]', context.course.code).should(
        'contain.text',
        'Curso actualizado desde interfaz',
      );
      cy.contains('button', /^Crear concepto$/).click();
      dialog().within(() => {
        cy.get('[name="name"]').type(context.concept.name.toUpperCase());
        cy.get('[name="description"]').type('Texto que debe conservarse');
        cy.contains('button', /^Guardar$/).click();
        cy.get('[role="alert"]').should('be.visible');
        cy.get('[name="description"]').should(
          'have.value',
          'Texto que debe conservarse',
        );
        cy.contains('button', /^Cancelar$/).click();
      });
      cy.contains('[data-cy="concept-card"]', context.concept.name).within(() =>
        cy.contains('button', 'Editar concepto').click(),
      );
      dialog().within(() => {
        cy.get('[name="description"]').clear().type('Descripción versionada');
        cy.contains('button', /^Guardar$/).click();
      });
      cy.get('[role="dialog"]').should('not.exist');
      cy.contains('[data-cy="concept-card"]', context.concept.name).should(
        'contain.text',
        'Descripción versionada',
      );
    });
  });

  it('IMP02-02 · Profesor configura su clase y ordena una publicación → conserva versiones y bloquea transiciones inválidas', () => {
    setup(false).then((context) => {
      visitAs(context.teacher, `/clases/${context.classroom.id}`);
      cy.contains('button', 'Configurar clase').click();
      dialog().within(() => {
        cy.get('[name="name"]')
          .clear()
          .type('Clase configurada por su profesor');
        cy.contains('button', /^Guardar$/).click();
      });
      cy.get('[role="dialog"]').should('not.exist');
      cy.contains('h1', 'Clase configurada por su profesor').should(
        'be.visible',
      );
      cy.contains('[data-cy="activity-card"]', context.activity.title).within(
        () => cy.contains('a', 'Abrir actividad').click(),
      );
      cy.contains('button', 'Editar actividad').click();
      dialog().within(() => {
        cy.get('[data-cy="activity-exercise-selected"]')
          .first()
          .contains('button', /^Bajar$/)
          .click();
        cy.get('[data-cy="activity-exercise-selected"]')
          .first()
          .should('contain.text', 'Segunda suma');
        cy.contains('button', 'Guardar borrador').click();
      });
      cy.get('[role="dialog"]').should('not.exist');
      cy.contains('button', 'Publicar actividad').click();
      dialog()
        .contains('button', /^Cancelar$/)
        .click();
      cy.contains('button', 'Publicar actividad').should('be.visible').click();
      dialog()
        .contains('button', /^Confirmar$/)
        .click();
      cy.get('[role="dialog"]').should('not.exist');
      cy.contains('Publicada').should('be.visible');
      cy.get('[data-cy="published-exercise"]')
        .first()
        .should('contain.text', 'Segunda suma');
      cy.contains('button', 'Editar actividad').should('not.exist');
      visitAs(context.teacher, `/ejercicios/${context.exercise.id}`);
      cy.contains('button', 'Crear nueva versión').click();
      dialog().within(() => {
        cy.get('[name="statement"]')
          .clear()
          .type('Enunciado para una nueva versión');
        cy.contains('button', 'Guardar nueva versión').click();
      });
      cy.get('[role="dialog"]').should('not.exist');
      cy.contains('Versión 2').should('be.visible');
      enroll(context);
      rest<Activity>(
        context.teacher,
        'GET',
        `/activities/${context.activity.id}`,
      ).then((published) => {
        const assignment = published.exercises.find(
          (item) => item.exerciseId === context.exercise.id,
        )!;
        visitAs(
          context.student,
          `/actividades/${published.id}/ejercicios/${assignment.id}`,
        );
      });
      cy.contains('Devuelve la suma de los dos argumentos.').should(
        'be.visible',
      );
      cy.contains('Enunciado para una nueva versión').should('not.exist');
    });
  });

  it('IMP02-03 · Estudiante confirma inscripción y edita → conserva borrador tras recargar y cerrar sesión sin revelar pruebas ocultas', () => {
    cy.visit('/acceso');
    cy.get('#email').type('correo-invalido');
    cy.get('#password').type('valor-de-prueba', { log: false });
    cy.contains('button', /^Iniciar sesión$/).click();
    cy.get<HTMLInputElement>('#email').should(($input) => {
      expect($input[0]!.validity.typeMismatch).to.equal(true);
      expect($input[0]!.validationMessage).not.to.equal('');
    });
    cy.get('#email').clear().type('estudiante@example.test');
    cy.get('#password').clear();
    cy.contains('button', /^Iniciar sesión$/).click();
    cy.get<HTMLInputElement>('#password').should(($input) => {
      expect($input[0]!.validity.valueMissing).to.equal(true);
      expect($input[0]!.validationMessage).not.to.equal('');
    });
    cy.location('pathname').should('equal', '/acceso');
    cy.contains('button', /^Cerrar sesión$/).should('not.exist');
    setup().then((context) => {
      visitAs(context.student, `/academia?org=${organizationId}`);
      cy.contains('button', 'Incorporarme a una clase').click();
      dialog().within(() => {
        cy.get('[name="joinCode"]').type(context.joinCode.code!, {
          log: false,
        });
        cy.contains('button', 'Revisar código').click();
        cy.contains(context.classroom.name).should('be.visible');
        cy.contains('button', /^Cancelar$/).click();
      });
      cy.contains('[data-cy="class-card"]', context.classroom.name).should(
        'not.exist',
      );
      cy.contains('button', 'Incorporarme a una clase').click();
      dialog().within(() => {
        cy.get('[name="joinCode"]').type(context.joinCode.code!, {
          log: false,
        });
        cy.contains('button', 'Revisar código').click();
        cy.contains('button', 'Confirmar incorporación').click();
        cy.contains('Incorporación confirmada').should('be.visible');
        cy.contains('a', `Abrir ${context.classroom.name}`).click();
      });
      cy.contains('[data-cy="activity-card"]', context.activity.title)
        .contains('a', 'Abrir actividad')
        .click();
      cy.get('[data-cy="published-exercise"]')
        .first()
        .contains('a', 'Abrir ejercicio')
        .click();
      cy.get('[data-cy="visible-test"]')
        .should('have.length', 1)
        .and('contain.text', 'visible-suma');
      cy.contains('hidden-sentinel-e2e').should('not.exist');
      cy.contains('98761').should('not.exist');
      cy.get('main#contenido').should('have.length', 1);
      cy.get('nav[aria-label="Navegación principal"]').should('be.visible');
      cy.get('main h1').should('have.length', 1);
      cy.contains('h2', 'Tu solución').should('be.visible');
      cy.get('label[for="student-code"]').should(
        'have.text',
        'Código JavaScript',
      );
      cy.get('[data-cy="student-code"]').should(
        'have.attr',
        'aria-describedby',
        'editor-help draft-status',
      );
      cy.get('#editor-help').should('contain.text', 'Tab permite salir');
      cy.get('#draft-status').should('have.attr', 'role', 'status');
      cy.contains('a', 'Volver a la actividad').focus();
      cy.press(Cypress.Keyboard.Keys.TAB);
      cy.get('[data-cy="student-code"]').should('have.focus');
      cy.press(Cypress.Keyboard.Keys.TAB);
      cy.contains('button', /^Ejecutar$/).should('have.focus');
      cy.press(Cypress.Keyboard.Keys.TAB);
      cy.get('[data-cy="submit-code"]').should('have.focus');
      cy.press(Cypress.Keyboard.Keys.TAB);
      cy.contains('button', 'Actualizar historial').should('have.focus');
      cy.press(Cypress.Keyboard.Keys.TAB);
      cy.contains('button', 'Descartar borrador').should('have.focus');
      cy.viewport(390, 844);
      cy.contains('Devuelve la suma de los dos argumentos.').should(
        'be.visible',
      );
      cy.get('[data-cy="student-code"]').should('be.visible');
      cy.document().should((document) => {
        expect(document.documentElement.scrollWidth).to.be.at.most(
          document.documentElement.clientWidth,
        );
      });
      cy.viewport(1280, 900);
      cy.get('[data-cy="student-code"]')
        .clear()
        .type(
          'module.exports.solve = function solve(a, b) { return a + b; };',
          {
            parseSpecialCharSequences: false,
          },
        );
      cy.contains('Borrador guardado en este navegador.').should('be.visible');
      cy.reload();
      cy.get('[data-cy="student-code"]').should(
        'have.value',
        'module.exports.solve = function solve(a, b) { return a + b; };',
      );
      cy.contains('button', 'Cerrar sesión').click();
      cy.location('pathname').should('equal', '/acceso');
      cy.task<Session>('identity:login', 'STUDENT', { log: false }).then(
        (session) => visitAs(session, editorPath(context)),
      );
      cy.get('[data-cy="student-code"]').should(
        'have.value',
        'module.exports.solve = function solve(a, b) { return a + b; };',
      );
      cy.contains('button', 'Descartar borrador').click();
      dialog()
        .contains('button', /^Cancelar$/)
        .click();
      cy.get('[data-cy="student-code"]').should(
        'contain.value',
        'return a + b;',
      );
      cy.contains('button', 'Descartar borrador').click();
      dialog().contains('button', 'Confirmar descarte').click();
      cy.get('[data-cy="student-code"]').should('contain.value', 'return 0;');
      cy.reload();
      cy.get('[data-cy="student-code"]').should('contain.value', 'return 0;');
      cy.contains('button', /^Ejecutar$/).should('be.enabled');
      cy.contains('button', /^Enviar intento$/).should('be.enabled');
    });
  });

  it('IMP02-04 · Cierre conserva contenido y borrador propio → editor queda solo lectura y otra cuenta no lo recupera', () => {
    setup().then((context) => {
      enroll(context);
      visitAs(context.student, editorPath(context));
      cy.get('[data-cy="student-code"]')
        .clear()
        .type('// borrador privado de estudiante A', {
          parseSpecialCharSequences: false,
        });
      rest<Activity>(
        context.teacher,
        'POST',
        `/activities/${context.activity.id}/close`,
        {},
        context.activity.revision,
      );
      cy.reload();
      cy.get('[data-cy="student-code"]').should(($editor) => {
        expect($editor).to.have.attr('readonly');
        expect($editor).to.have.value('// borrador privado de estudiante A');
      });
      cy.contains('Solo lectura:').should('be.visible');
      visitAs(context.admin, editorPath(context));
      cy.get('[role="alert"]').should('be.visible');
      cy.get('[data-cy="student-code"]').should('not.exist');
      cy.contains('// borrador privado de estudiante A').should('not.exist');
    });
  });

  it('IMP02-05 · Borrador vencido o almacenamiento fallido → informa el problema y mantiene la plantilla', () => {
    setup().then((context) => {
      enroll(context);
      visitAs(context.student, editorPath(context));
      cy.get('[data-cy="student-code"]')
        .clear()
        .type('// borrador que vencera');
      cy.window().then((window) => {
        const key = Object.keys(window.localStorage).find((item) =>
          item.startsWith(draftPrefix),
        )!;
        window.localStorage.setItem(
          key,
          JSON.stringify({
            version: 1,
            code: '// vencido',
            updatedAt: Date.now() - 30 * 86400000 - 1,
          }),
        );
      });
      cy.reload();
      cy.contains('El borrador venció').should('be.visible');
      cy.get('[data-cy="student-code"]').should('contain.value', 'return 0;');
      visitAs(context.student, editorPath(context), (window) => {
        const original = window.Storage.prototype.getItem;
        window.Storage.prototype.getItem = function (key: string) {
          if (key.startsWith(draftPrefix))
            throw new Error('Almacenamiento local de prueba no disponible');
          return original.call(this, key);
        };
        const write = window.Storage.prototype.setItem;
        window.Storage.prototype.setItem = function (
          key: string,
          value: string,
        ) {
          if (key.startsWith(draftPrefix))
            throw new Error('Cuota local de prueba agotada');
          return write.call(this, key, value);
        };
      });
      cy.contains('No se pudo recuperar el borrador.').should('be.visible');
      cy.get('[data-cy="student-code"]').should('contain.value', 'return 0;');
      cy.get('[data-cy="student-code"]')
        .clear()
        .type('// trabajo solo en memoria');
      cy.contains('No se pudo guardar el borrador local.').should('be.visible');
      cy.contains('button', 'Actualizar disponibilidad').click();
      cy.get('[data-cy="student-code"]').should(($editor) => {
        expect($editor).not.to.have.attr('readonly');
        expect($editor).to.have.value('// trabajo solo en memoria');
      });
      cy.intercept(
        {
          method: 'GET',
          url: `**/api/v1/activities/${context.activity.id}/exercises/${context.activity.exercises[0]!.id}`,
          times: 1,
        },
        { forceNetworkError: true },
      ).as('editorOffline');
      cy.contains('button', 'Actualizar disponibilidad').click();
      cy.wait('@editorOffline');
      cy.get('[data-cy="student-code"]').should(($editor) => {
        expect($editor).to.have.attr('readonly');
        expect($editor).to.have.value('// trabajo solo en memoria');
      });
      cy.contains('button', 'Actualizar disponibilidad').click();
      cy.get('[data-cy="student-code"]').should(($editor) => {
        expect($editor).not.to.have.attr('readonly');
        expect($editor).to.have.value('// trabajo solo en memoria');
      });
    });
  });

  it('IMP02-06 · Clase archivada y código inválido → conserva lectura y rechaza operaciones con campos intactos', () => {
    setup().then((context) => {
      rest<Activity>(
        context.teacher,
        'POST',
        `/activities/${context.activity.id}/close`,
        {},
        context.activity.revision,
      );
      visitAs(context.admin, `/clases/${context.classroom.id}`);
      cy.contains('button', 'Archivar clase').click();
      dialog().within(() => {
        cy.get('[name="reason"]').type('Cierre académico de prueba');
        cy.contains('button', /^Guardar$/).click();
      });
      cy.get('[role="dialog"]').should('not.exist');
      cy.contains('Archivada · Solo lectura').should('be.visible');
      visitAs(context.teacher, `/clases/${context.classroom.id}`);
      cy.contains('button', 'Configurar clase').should('not.exist');
      cy.contains('button', 'Generar código').should('not.exist');
      cy.contains('[data-cy="activity-card"]', context.activity.title).should(
        'be.visible',
      );
      visitAs(context.student, `/academia?org=${organizationId}`);
      cy.contains('button', 'Incorporarme a una clase').click();
      dialog().within(() => {
        cy.get('[name="joinCode"]').type(context.joinCode.code!, {
          log: false,
        });
        cy.contains('button', 'Revisar código').click();
        cy.get('[role="alert"]').should('be.visible');
        cy.get('[name="joinCode"]').should('have.value', context.joinCode.code);
      });
    });
  });

  it('IMP02-07 · Navegar al editor en entorno local → registra veinte muestras completas y p95 menor a tres segundos', () => {
    setup().then((context) => {
      enroll(context);
      visitAs(context.student, `/academia?org=${organizationId}`);
      cy.contains('h1', 'Clases y contenido').should('be.visible');
      const samples: number[] = [];
      // One signed-in user; first editor navigation is kept as a cold sample.
      // Timing starts before navigation and includes auth/API/content readiness.
      for (let index = 0; index < 20; index += 1) {
        cy.visit(`/academia?org=${organizationId}`);
        cy.contains('h1', 'Clases y contenido').should('be.visible');
        cy.then(() => {
          const start = performance.now();
          cy.visit(editorPath(context));
          return cy
            .get('[data-cy="student-code"]')
            .should('be.visible')
            .and('not.have.attr', 'readonly')
            .then(() => {
              samples.push(performance.now() - start);
            });
        });
      }
      cy.then(() =>
        cy.task(
          'academic:performance',
          { operation: 'editor', samples },
          { log: false },
        ),
      );
      cy.then(() => {
        expect(samples).to.have.length(20);
        const sorted = [...samples].sort((a, b) => a - b);
        expect(
          sorted[Math.ceil(sorted.length * 0.95) - 1],
          'p95 de navegación local en milisegundos',
        ).to.be.lessThan(3000);
      });
    });
  });

  it('IMP02-08 · La ventana UTC abre y cierra durante la visita → cambia edición sin recargar ni perder el borrador', () => {
    setup(false).then((context) => {
      enroll(context).then(() => {
        const opensAt = Date.now() + 20_000;
        return rest<Activity>(
          context.teacher,
          'PATCH',
          `/activities/${context.activity.id}`,
          {
            opensAt: new Date(opensAt).toISOString(),
            closesAt: new Date(opensAt + 10_000).toISOString(),
          },
          context.activity.revision,
        ).then((draft) =>
          rest<Activity>(
            context.teacher,
            'POST',
            `/activities/${draft.id}/publish`,
            {},
            draft.revision,
          ).then((activity) => {
            visitAs(context.student, editorPath({ ...context, activity }));
            cy.get('[data-cy="student-code"]')
              .should('be.visible')
              .and('have.attr', 'readonly');
            cy.get('[data-cy="student-code"]', { timeout: 30_000 }).should(
              'not.have.attr',
              'readonly',
            );
            cy.get('[data-cy="student-code"]')
              .clear()
              .type('module.exports.solve = () => 42;', {
                parseSpecialCharSequences: false,
              });
            cy.get('[data-cy="student-code"]', { timeout: 20_000 }).should(
              ($editor) => {
                expect($editor).to.have.attr('readonly');
                expect($editor).to.have.value(
                  'module.exports.solve = () => 42;',
                );
              },
            );
            cy.contains('[role="status"]', 'fuera de su ventana').should(
              'be.visible',
            );
          }),
        );
      });
    });
  });
});
