// Generated by Cypress Author on 2026-09-10 for IMP-00.05.
import fixture from '../../fixtures/foundation/identity.json';

type Account = (typeof fixture.users)[number];
const organizationA = fixture.organizations[0]!;
const organizationB = fixture.organizations[1]!;
const accounts = fixture.users.filter(
  (user) => user.organizationId === organizationA.id,
);
const student = accounts.find((user) => user.role === 'STUDENT')!;
const roleNames: Record<string, string> = {
  ADMIN: 'Administrador',
  TEACHER: 'Profesor',
  STUDENT: 'Estudiante',
};
const accessCases = [
  { id: 'FND-02', role: 'ADMIN' },
  { id: 'FND-03', role: 'TEACHER' },
  { id: 'FND-04', role: 'STUDENT' },
] as const;

function login(account: Account) {
  cy.visit('/acceso');
  cy.get('#email').should('be.visible').type(account.email, { log: false });
  cy.env(['fixturePassword'], { log: false }).then(({ fixturePassword }) => {
    expect(
      typeof fixturePassword === 'string' && fixturePassword.length > 0,
      'fixture disponible',
    ).to.equal(true);
    cy.get('#password')
      .should('have.attr', 'type', 'password')
      .type(fixturePassword as string, {
        log: false,
        parseSpecialCharSequences: false,
      });
  });
  cy.contains('button', /^Iniciar sesión$/).click();
  cy.contains('h2', account.displayName).should('be.visible');
  cy.contains('h3', organizationA.name).should('be.visible');
}

function logout(account: Account) {
  cy.contains('button', /^Cerrar sesión$/).click();
  cy.contains(
    '[role="status"]',
    'La sesión se cerró en este navegador.',
  ).should('be.visible');
  cy.contains('h2', account.displayName).should('not.exist');
  cy.contains('h3', organizationA.name).should('not.exist');
  cy.focused().should('have.attr', 'id', 'email');
}

describe('Fundación local integrada', () => {
  it('FND-01 · Consultar estado → API y datos disponibles', () => {
    cy.visit('/');
    cy.contains('h1', 'Una base para empezar.').should('be.visible');
    cy.get('[role="status"]').should(($statuses) => {
      expect($statuses).to.have.length(2);
      for (const status of $statuses)
        expect(status.textContent?.trim()).to.equal('Disponible');
    });
    cy.env(['apiBaseUrl'], { log: false }).then(({ apiBaseUrl }) => {
      for (const path of ['/health/live', '/health/ready']) {
        cy.request({
          url: `${apiBaseUrl}${path}`,
          log: false,
          failOnStatusCode: false,
        }).then((response) => {
          expect(response.status).to.equal(200);
          expect(response.body.data?.status === 'ok').to.equal(true);
          expect(typeof response.body.requestId === 'string').to.equal(true);
        });
      }
    });
  });

  accessCases.forEach(({ id, role }) => {
    it(`${id} · Acceso ${roleNames[role]} → perfil, organización y cierre verificados`, () => {
      const account = accounts.find((candidate) => candidate.role === role);
      if (!account)
        throw new Error(
          'Falta una cuenta requerida en el fixture de fundación.',
        );
      login(account);
      cy.contains('dd', roleNames[account.role]!).should('be.visible');
      cy.reload();
      cy.contains('h2', account.displayName).should('be.visible');
      cy.contains('h3', organizationA.name).should('be.visible');
      logout(account);
      cy.reload();
      cy.get('#email').should('be.visible');
      cy.contains('h2', account.displayName).should('not.exist');
    });
  });

  it('FND-05 · Contraseña incorrecta → rechazo sin perfil ni sesión', () => {
    cy.visit('/acceso');
    cy.get('#email').should('be.visible').type(student.email, { log: false });
    cy.get('#password').type('deliberately-invalid-foundation-password', {
      log: false,
    });
    cy.contains('button', /^Iniciar sesión$/).click();
    cy.contains(
      '[role="alert"]',
      'No pudimos iniciar sesión con ese correo y contraseña.',
    ).should('be.visible');
    cy.get('#password').should('have.value', '');
    cy.contains('h2', student.displayName).should('not.exist');
    cy.contains('button', /^Cerrar sesión$/).should('not.exist');
  });

  it('FND-06 · Consultar otra organización → mismo 404 que un recurso inexistente', () => {
    login(student);
    cy.env(['apiBaseUrl'], { log: false }).then(({ apiBaseUrl }) => {
      cy.window({ log: false }).then((window) => {
        const session = JSON.parse(
          window.localStorage.getItem('alunza.auth.127.0.0.1:16421') || '{}',
        );
        const accessToken: unknown = session.access_token;
        expect(
          typeof accessToken === 'string' && accessToken.length > 0,
          'sesión emitida por Auth',
        ).to.equal(true);
        const requestOrganization = (id: string) =>
          cy.request({
            url: `${apiBaseUrl}/api/v1/organizations/${id}`,
            headers: { Authorization: `Bearer ${accessToken}` },
            failOnStatusCode: false,
            log: false,
          });
        return requestOrganization(organizationB.id).then((foreign) => {
          return requestOrganization(
            '99999999-9999-4999-8999-999999999999',
          ).then((missing) => {
            for (const response of [foreign, missing]) {
              expect(response.status).to.equal(404);
              expect(
                response.body.error?.code === 'RESOURCE_NOT_FOUND',
              ).to.equal(true);
              expect(response.body.data === undefined).to.equal(true);
              expect(
                JSON.stringify(response.body).includes(organizationB.name),
              ).to.equal(false);
              expect(
                JSON.stringify(response.body).includes(String(accessToken)),
              ).to.equal(false);
            }
            expect(
              JSON.stringify(foreign.body.error) ===
                JSON.stringify(missing.body.error),
              'rechazos indistinguibles',
            ).to.equal(true);
          });
        });
      });
    });
    logout(student);
  });

  it('FND-07 · API caída durante acceso → datos retirados y recuperación al reintentar', () => {
    login(student);
    cy.task('foundation:apiStop', null, { log: false });
    cy.contains('button', /^Actualizar acceso$/).click();
    cy.contains('[role="alert"]', 'No pudimos conectar con la API.').should(
      'be.visible',
    );
    cy.contains('h2', student.displayName).should('not.exist');
    cy.contains('h3', organizationA.name).should('not.exist');
    cy.task('foundation:apiStart', null, { log: false });
    cy.contains('button', /^Reintentar acceso$/).click();
    cy.contains('h2', student.displayName).should('be.visible');
    cy.contains('h3', organizationA.name).should('be.visible');
    logout(student);
  });

  it('FND-08 · API caída en Estado → indisponibilidad real y comprobación recuperada', () => {
    cy.task('foundation:apiStop', null, { log: false });
    cy.visit('/');
    cy.get('[role="status"]').should(($statuses) => {
      expect($statuses).to.have.length(2);
      for (const status of $statuses)
        expect(status.textContent?.trim()).to.equal('No disponible');
    });
    cy.task('foundation:apiStart', null, { log: false });
    cy.contains('button', /^Volver a comprobar$/).click();
    cy.get('[role="status"]').should(($statuses) => {
      expect($statuses).to.have.length(2);
      for (const status of $statuses)
        expect(status.textContent?.trim()).to.equal('Disponible');
    });
  });
});
