// Generated by Cypress Author on 2026-09-11 for IMP-01.
import type { Session } from '@supabase/supabase-js';
import fixture from '../../fixtures/foundation/identity.json';

interface Institution {
  id: string;
  code: string;
  name: string;
  grantId: string;
  email: string;
  ownerId: string;
  studentId: string;
  foreignId: string;
}
function openAsAdmin(path: string) {
  return cy
    .task<Session>('identity:login', 'ADMIN', { log: false })
    .then((session) => {
      cy.visit(path, {
        onBeforeLoad(window) {
          window.localStorage.setItem(
            'alunza.auth.127.0.0.1:16421',
            JSON.stringify(session),
          );
        },
      });
    });
}
function prepare() {
  return cy.task<Institution>('identity:prepare', null, { log: false });
}
function dialog() {
  return cy.get('[role="dialog"]').should('be.visible');
}
function invite(email: string) {
  cy.contains('button', /^Invitar usuario$/).click();
  dialog().within(() => {
    cy.get('[name="email"]').type(email, { log: false });
    cy.get('[name="role"]').select('STUDENT');
    cy.contains('button', /^Enviar invitación$/).click();
  });
  cy.get('[role="dialog"]').should('not.exist');
  cy.contains('[data-cy="invitation-row"]', email).should('be.visible');
}
function formLogin(email: string) {
  cy.visit('/acceso');
  cy.get('#email').type(email, { log: false });
  cy.env(['fixturePassword'], { log: false }).then(({ fixturePassword }) =>
    cy.get('#password').type(String(fixturePassword), {
      log: false,
      parseSpecialCharSequences: false,
    }),
  );
  cy.contains('button', /^Iniciar sesión$/).click();
}

describe('IMP-01 · Gobierno institucional integrado', () => {
  it('IMP01-01 · Crear, editar y archivar → persiste y queda solo lectura', () => {
    prepare().then((org) => {
      openAsAdmin('/administracion/organizaciones');
      cy.contains('button', /^Crear organización$/).click();
      dialog().within(() => {
        cy.get('[name="grantId"]').should('have.value', org.grantId);
        cy.get('[name="name"]').type('Nueva institución E2E');
        cy.get('[name="code"]').type(`NEW-${org.code}`);
        cy.contains('button', /^Crear organización$/).click();
      });
      cy.get('[role="dialog"]').should('not.exist');
      cy.contains('[data-cy="organization-card"]', `NEW-${org.code}`).within(
        () => cy.contains('button', /^Editar$/).click(),
      );
      dialog().within(() => {
        cy.get('[name="name"]').clear().type('Institución actualizada');
        cy.contains('button', /^Guardar cambios$/).click();
      });
      cy.get('[role="dialog"]').should('not.exist');
      cy.reload();
      cy.contains('[data-cy="organization-card"]', `NEW-${org.code}`).within(
        () => {
          cy.contains('Institución actualizada').should('be.visible');
          cy.contains('button', /^Archivar$/).click();
        },
      );
      dialog().within(() => {
        cy.get('[name="reason"]').type('Cierre de institución de prueba');
        cy.contains('button', /^Confirmar archivo$/).click();
      });
      cy.get('[role="dialog"]').should('not.exist');
      cy.contains('[data-cy="organization-card"]', `NEW-${org.code}`).within(
        () => {
          cy.contains('Archivada · Solo lectura').should('be.visible');
          cy.contains('button', /^Editar$/).should('not.exist');
          cy.contains('a', /^Consultar usuarios e invitaciones$/).click();
        },
      );
      cy.get('[data-cy="member-row"]').should('have.length', 1);
      cy.contains('h2', /^Invitaciones$/).should('be.visible');
      cy.contains('button', /^Invitar usuario$/).should('not.exist');
      cy.contains('button', /^Cambiar acceso$/).should('not.exist');
    });
  });
  it('IMP01-02 · Datos inválidos y código duplicado → error corregible sin perder formulario', () => {
    prepare().then((org) => {
      openAsAdmin('/administracion/organizaciones');
      cy.contains('button', /^Crear organización$/).click();
      dialog().within(() => {
        cy.get('[name="grantId"]').should('have.value', org.grantId);
        cy.get('[name="name"]').should('have.attr', 'required');
        cy.get('[name="name"]').type('Nombre que debe conservarse');
        cy.get('[name="code"]').type(fixture.organizations[0]!.code);
        cy.contains('button', /^Crear organización$/).click();
        cy.get('[role="alert"]').should('be.visible');
        cy.get('[name="name"]').should(
          'have.value',
          'Nombre que debe conservarse',
        );
      });
    });
  });
  it('IMP01-03 · URL y API ajenas → no muestran organización ni miembros', () => {
    prepare().then((org) => {
      openAsAdmin(`/administracion/organizaciones/${org.foreignId}/usuarios`);
      cy.get('[role="alert"]').should('be.visible');
      cy.contains(fixture.organizations[1]!.name).should('not.exist');
      cy.task<Session>('identity:login', 'ADMIN', { log: false }).then(
        (session) => {
          cy.env(['apiBaseUrl'], { log: false }).then(({ apiBaseUrl }) => {
            cy.request({
              url: `${apiBaseUrl}/api/v1/organizations/${org.foreignId}/members`,
              headers: { Authorization: `Bearer ${session.access_token}` },
              failOnStatusCode: false,
              log: false,
            }).then((r) => {
              expect(r.status).to.equal(404);
              expect(r.body.data === undefined).to.equal(true);
            });
          });
        },
      );
    });
  });
  it('IMP01-04 · INVITED y DISABLED → sesión sin acceso de producto', () => {
    for (const state of ['INVITED', 'DISABLED']) {
      cy.task<{ email: string }>('identity:inactiveAccount', state, {
        log: false,
      }).then(({ email }) => {
        cy.clearAllLocalStorage({ log: false });
        formLogin(email);
        cy.get('[role="alert"]').should('be.visible');
        cy.contains('Cuenta inactiva de prueba').should('not.exist');
      });
    }
  });
  it('IMP01-05 · Invitación local → aceptación en navegador limpio y deshabilitación', () => {
    prepare().then((org) => {
      openAsAdmin(`/administracion/organizaciones/${org.id}/usuarios`);
      invite(org.email);
      cy.task<{ url: string }>(
        'identity:mail',
        { email: org.email },
        { log: false },
      ).then(({ url }) => {
        cy.clearAllLocalStorage({ log: false });
        cy.clearAllCookies({ log: false });
        cy.visit(url, { log: false });
        cy.contains('button', /^Continuar$/).click();
        cy.get('[name="displayName"]').type('Estudiante de invitación');
        cy.env(['fixturePassword'], { log: false }).then(
          ({ fixturePassword }) => {
            cy.get('[name="password"]').type(String(fixturePassword), {
              log: false,
              parseSpecialCharSequences: false,
            });
            cy.get('[name="passwordConfirmation"]').type(
              String(fixturePassword),
              { log: false, parseSpecialCharSequences: false },
            );
          },
        );
        cy.contains('button', /^Aceptar invitación$/).click();
        cy.contains('Tu acceso a la organización está activo.').should(
          'be.visible',
        );
        cy.contains('a', /^Ir al inicio$/).click();
        cy.contains('h2', 'Estudiante de invitación').should('be.visible');
        cy.contains('h3', org.name).should('be.visible');
      });
      openAsAdmin(`/administracion/organizaciones/${org.id}/usuarios`);
      cy.contains('[data-cy="member-row"]', org.email).within(() =>
        cy.contains('button', /^Cambiar acceso$/).click(),
      );
      dialog().within(() => {
        cy.get('[name="state"]').select('DISABLED');
        cy.contains('button', /^Guardar cambios$/).click();
      });
      cy.get('[role="dialog"]').should('not.exist');
      cy.contains('[data-cy="member-row"]', org.email).should(
        'contain.text',
        'Deshabilitado',
      );
    });
  });
  it('IMP01-06 · Deshabilitar último ADMIN → rechazo y acceso conservado', () => {
    prepare().then((org) => {
      openAsAdmin(`/administracion/organizaciones/${org.id}/usuarios`);
      cy.get('[data-cy="member-row"]')
        .first()
        .within(() => cy.contains('button', /^Cambiar acceso$/).click());
      dialog().within(() => {
        cy.get('[name="state"]').select('DISABLED');
        cy.contains('button', /^Guardar cambios$/).click();
        cy.get('[role="alert"]').should('contain.text', 'administrador');
      });
      cy.reload();
      cy.get('[data-cy="member-row"]').first().should('contain.text', 'Activo');
    });
  });
  it('IMP01-07 · Invitación pendiente → reenvío y revocación tienen estado real', () => {
    prepare().then((org) => {
      openAsAdmin(`/administracion/organizaciones/${org.id}/usuarios`);
      invite(org.email);
      cy.task('identity:mail', { email: org.email }, { log: false });
      cy.reload();
      cy.contains('[data-cy="invitation-row"]', org.email).within(() =>
        cy.contains('button', /^Reenviar$/).click(),
      );
      dialog().within(() =>
        cy.contains('button', /^Confirmar reenvío$/).click(),
      );
      cy.get('[role="dialog"]').should('not.exist');
      cy.contains('button', /^Actualizar estados$/).click();
      cy.contains('[data-cy="invitation-row"]', org.email).within(() =>
        cy.contains('button', /^Revocar$/).click(),
      );
      dialog().within(() =>
        cy.contains('button', /^Confirmar revocación$/).click(),
      );
      cy.get('[role="dialog"]').should('not.exist');
      cy.contains('[data-cy="invitation-row"]', org.email).should(
        'contain.text',
        'Revocada',
      );
    });
  });
  it('IMP01-08 · Archivo con invitación vigente → rechazo hasta resolver dependencia', () => {
    prepare().then((org) => {
      openAsAdmin(`/administracion/organizaciones/${org.id}/usuarios`);
      invite(org.email);
      cy.visit('/administracion/organizaciones');
      cy.contains('[data-cy="organization-card"]', org.code).within(() =>
        cy.contains('button', /^Archivar$/).click(),
      );
      dialog().within(() => {
        cy.get('[name="reason"]').type('Comprobar dependencias');
        cy.contains('button', /^Confirmar archivo$/).click();
        cy.get('[role="alert"]').should('be.visible');
      });
      cy.reload();
      cy.contains('[data-cy="organization-card"]', org.code).should(
        'contain.text',
        'Activa',
      );
    });
  });
});
