// Generated by Cypress Author on 2026-09-28 for IMP-02.
import type { Session } from '@supabase/supabase-js';
interface AcademicFixture {
  organization: { id: string };
  course: { id: string };
  classroom: { id: string; revision: number };
  concept: { id: string; currentVersionId: string };
  exercise: { id: string; currentVersionId: string };
  activity: { id: string; revision: number; exercises: { id: string }[] };
  joinCode: { code: string };
}
const prepare = (options: Record<string, boolean> = {}) =>
  cy.task<AcademicFixture>('academic:prepare', options, { log: false });
function openAs(role: string, path: string, storageFailure?: 'read' | 'write') {
  return cy
    .task<Session>('academic:login', role, { log: false })
    .then((session) => {
      cy.visit(path, {
        onBeforeLoad(window) {
          window.localStorage.setItem(
            'alunza.auth.127.0.0.1:16421',
            JSON.stringify(session),
          );
          if (storageFailure) {
            const storage = window.sessionStorage;
            const method = storageFailure === 'read' ? 'getItem' : 'setItem';
            // Only the local draft store fails; every backend request stays real.
            Object.defineProperty(storage, method, {
              configurable: true,
              value() {
                throw new Error('Storage unavailable for controlled test');
              },
            });
          }
        },
      });
    });
}
const basePath = (f: AcademicFixture) => `/academia/${f.organization.id}`;
const solutionPath = (f: AcademicFixture) =>
  `${basePath(f)}/actividades/${f.activity.id}/ejercicios/${f.activity.exercises[0]!.id}`;
const dialog = () => cy.get('[role="dialog"]').should('be.visible');
const replace = (name: string, value: string) =>
  cy
    .get(`[name="${name}"]`)
    .clear()
    .type(value, { parseSpecialCharSequences: false });

function signInStudentWithoutReload() {
  cy.get('#email').type('student.a@alunza.test', { log: false });
  cy.env(['fixturePassword'], { log: false }).then(({ fixturePassword }) =>
    cy.get('#password').type(String(fixturePassword), {
      log: false,
      parseSpecialCharSequences: false,
    }),
  );
  cy.contains('button', /^Iniciar sesión$/).click();
  cy.location('pathname').should('eq', '/inicio');
}

function openSolutionFromHome(f: AcademicFixture) {
  cy.get('[name="organization"]').select(f.organization.id);
  cy.get(`a[href="${basePath(f)}/clases/${f.classroom.id}"]`).click();
  cy.get(`a[href="${basePath(f)}/actividades/${f.activity.id}"]`).click();
  cy.get(`a[href="${solutionPath(f)}"]`).click();
}

describe('IMP-02 · preparación académica con servicios reales', () => {
  it('IMP02-01 · Administrar cursos y conceptos → cambios y versiones recuperables', () => {
    prepare().then((f) => {
      openAs('admin', basePath(f));
      cy.contains('button', /^Crear curso$/).click();
      dialog().within(() => {
        cy.get('[name="code"]').type('CURSO-E2E');
        cy.get('[name="name"]').type('Curso creado desde interfaz');
        cy.get('[name="academicPeriod"]').type('2026-2');
        cy.contains('button', /^Guardar curso$/).click();
      });
      cy.get('[role="dialog"]').should('not.exist');
      cy.reload();
      cy.contains(
        '[data-cy="course-row"]',
        'Curso creado desde interfaz',
      ).should('be.visible');
      cy.screenshot('imp02-admin-cursos', { capture: 'viewport' });
      cy.visit(`${basePath(f)}/conceptos`);
      cy.contains('button', /^Crear concepto$/).click();
      dialog().within(() => {
        cy.get('[name="name"]').type('Iteración E2E');
        cy.get('[name="description"]').type('Repetición controlada');
        cy.contains('button', /^Guardar concepto$/).click();
      });
      cy.get('[role="dialog"]').should('not.exist');
      cy.contains('[data-cy="concept-row"]', 'Iteración E2E').within(() =>
        cy.contains('button', /^Editar concepto$/).click(),
      );
      dialog().within(() => {
        replace('name', 'Iteración revisada');
        cy.contains('button', /^Guardar concepto$/).click();
      });
      cy.get('[role="dialog"]').should('not.exist');
      cy.reload();
      cy.contains('[data-cy="concept-row"]', 'Iteración revisada').should(
        'contain.text',
        'Versión 2',
      );
      cy.screenshot('imp02-admin-conceptos', { capture: 'viewport' });
    });
  });
  it('IMP02-02 · Profesor crea y configura clase → genera código vigente', () => {
    prepare().then((f) => {
      openAs('teacher', basePath(f));
      cy.contains('button', /^Crear clase$/).click();
      dialog().within(() => {
        cy.get('[name="courseId"]').select(f.course.id);
        cy.get('[name="code"]').type('CLASE-E2E');
        cy.get('[name="name"]').type('Clase creada desde interfaz');
        cy.contains('button', /^Guardar clase$/).click();
      });
      cy.get('[role="dialog"]').should('not.exist');
      cy.reload();
      cy.contains(
        '[data-cy="class-row"]',
        'Clase creada desde interfaz',
      ).within(() => cy.contains('a', /^Abrir clase$/).click());
      cy.contains('button', /^Editar clase$/).click();
      dialog().within(() => {
        replace('name', 'Clase revisada');
        cy.contains('button', /^Guardar clase$/).click();
      });
      cy.get('[role="dialog"]').should('not.exist');
      cy.contains('h1', 'Clase revisada').should('be.visible');
      cy.contains('button', /^Generar código$/).click();
      cy.get('[name="issuedCode"]')
        .invoke('val')
        .should('match', /^[A-Z0-9]{8,}$/);
      cy.contains('button', /^Revocar código$/).click();
      dialog().within(() =>
        cy.contains('button', /^Confirmar revocar código$/).click(),
      );
      cy.get('[role="dialog"]').should('not.exist');
      cy.contains('Revocado').should('be.visible');
    });
  });
  it('IMP02-03 · Estudiante verifica y confirma código → clase incorporada una sola vez', () => {
    prepare({ enroll: false }).then((f) => {
      openAs('student', basePath(f));
      cy.get('[name="code"]').type(f.joinCode.code, { log: false });
      cy.contains('button', /^Verificar código$/).click();
      cy.get('[aria-label="Confirmar incorporación"]').within(() => {
        cy.contains('Clase de prueba').should('be.visible');
        cy.contains('button', /^Cancelar$/).click();
      });
      cy.get('[data-cy="class-row"]').should('not.exist');
      cy.contains('button', /^Verificar código$/).click();
      cy.contains('button', /^Confirmar incorporación$/).click();
      cy.contains('h1', 'Clase de prueba').should('be.visible');
      cy.visit(basePath(f));
      cy.get('[data-cy="class-row"]').should('have.length', 1);
      cy.get('[name="code"]').type(f.joinCode.code, { log: false });
      cy.contains('button', /^Verificar código$/).click();
      cy.contains('button', /^Abrir clase existente$/).click();
      cy.contains('h1', 'Clase de prueba').should('be.visible');
    });
  });
  it('IMP02-04 · Crear y versionar ejercicio → definición y pruebas conservadas', () => {
    prepare().then((f) => {
      openAs('teacher', `${basePath(f)}/ejercicios/nuevo`);
      cy.get('[name="title"]').type('Ejercicio creado desde interfaz');
      cy.get('[name="statement"]').type('Retorna el doble del número.');
      replace('starterCode', 'function solve(n) { return n * 2; }');
      cy.get(
        `[name="conceptVersionIds"][value="${f.concept.currentVersionId}"]`,
      ).check();
      replace('tests.0.args', '[2]');
      replace('tests.0.expected', '4');
      cy.contains('button', /^Agregar prueba$/).click();
      cy.get('[name="tests.1.visibility"]').select('HIDDEN');
      replace('tests.1.args', '[37]');
      replace('tests.1.expected', '74');
      cy.contains('button', /^Guardar ejercicio$/).click();
      cy.contains('h1', 'Ejercicio creado desde interfaz').should('be.visible');
      replace('title', 'Ejercicio revisado');
      cy.contains('button', /^Guardar nueva versión$/).click();
      cy.contains('h1', 'Ejercicio revisado').should('be.visible');
      cy.reload();
      cy.get('[name="tests.1.visibility"]').should('have.value', 'HIDDEN');
      cy.get('[name="tests.1.expected"]').should('have.value', '74');
      cy.contains('Versión 2').should('be.visible');
    });
  });
  it('IMP02-05 · Componer y publicar actividad → orden confirmado y cierre definitivo', () => {
    prepare({ published: false }).then((f) => {
      cy.task<{ status: number; data: { currentVersionId: string } }>(
        'academic:request',
        {
          role: 'teacher',
          path: `/organizations/${f.organization.id}/exercises`,
          options: {
            method: 'POST',
            key: f.classroom.id,
            body: {
              title: 'Duplicar un valor',
              statement: 'Implementa solve(n) y retorna el doble.',
              starterCode: 'function solve(n) {}',
              difficulty: 'BASIC',
              conceptVersionIds: [f.concept.currentVersionId],
              tests: [
                {
                  visibility: 'VISIBLE',
                  args: [4],
                  expected: 8,
                  comparator: 'EXACT_DEEP',
                },
                {
                  visibility: 'HIDDEN',
                  args: [19],
                  expected: 38,
                  comparator: 'EXACT_DEEP',
                },
              ],
            },
          },
        },
        { log: false },
      ).then((second) => {
        expect(second.status).to.eq(201);
        openAs('teacher', `${basePath(f)}/actividades/${f.activity.id}`);
        cy.get('[name="title"]').should('have.value', 'Primera actividad');
        cy.get('[name="exerciseChoice"]').select(second.data.currentVersionId);
        cy.contains('button', /^Agregar ejercicio$/).click();
        cy.get('[aria-label="Subir Duplicar un valor"]').click();
        cy.get('[data-cy="assigned-exercise-row"]')
          .should('have.length', 2)
          .first()
          .should('contain.text', 'Duplicar un valor');
        cy.intercept('PATCH', `**/api/v1/activities/${f.activity.id}`).as(
          'saveOrderedActivity',
        );
        cy.contains('button', /^Guardar borrador$/).click();
        cy.wait('@saveOrderedActivity')
          .its('response.statusCode')
          .should('eq', 200);
        cy.reload();
        cy.get('[data-cy="assigned-exercise-row"]')
          .should('have.length', 2)
          .first()
          .should('contain.text', 'Duplicar un valor');
        cy.get('[data-cy="assigned-exercise-row"]')
          .eq(1)
          .should('contain.text', 'Sumar dos valores');
        cy.contains('button', /^Publicar actividad$/).click();
        dialog().within(() => cy.contains('button', /^Cancelar$/).click());
        cy.get('[role="dialog"]').should('not.exist');
        cy.task<{
          status: number;
          data: { state: string; exercises: { title: string }[] };
        }>(
          'academic:request',
          { role: 'teacher', path: `/activities/${f.activity.id}` },
          { log: false },
        ).then((saved) => {
          expect(saved.status).to.eq(200);
          expect(saved.data.state).to.eq('DRAFT');
          expect(saved.data.exercises.map((item) => item.title)).to.deep.eq([
            'Duplicar un valor',
            'Sumar dos valores',
          ]);
        });
        cy.contains('button', /^Publicar actividad$/).click();
        dialog().within(() =>
          cy.contains('button', /^Confirmar publicar actividad$/).click(),
        );
        cy.get('[role="dialog"]').should('not.exist');
        cy.get('[data-cy="published-exercise-row"]')
          .should('have.length', 2)
          .first()
          .should('contain.text', 'Duplicar un valor');
        cy.get('[data-cy="published-exercise-row"]')
          .eq(1)
          .should('contain.text', 'Sumar dos valores');
        cy.contains('button', /^Cerrar actividad$/).click();
        dialog().within(() =>
          cy.contains('button', /^Confirmar cerrar actividad$/).click(),
        );
        cy.get('[role="dialog"]').should('not.exist');
        cy.contains('[role="status"]', 'Cerrada').should('be.visible');
        cy.contains('button', /^Publicar actividad$/).should('not.exist');
      });
    });
  });
  it('IMP02-06 · Editar y recargar → borrador propio recuperado y teclado sin trampa', () => {
    prepare().then((f) => {
      openAs('student', solutionPath(f));
      cy.get('[data-cy="solution-code"]')
        .should('be.visible')
        .clear()
        .type('function solve(a, b) { return a + b + 42; }', {
          parseSpecialCharSequences: false,
        });
      cy.contains('Borrador guardado en esta pestaña.').should('be.visible');
      cy.reload();
      cy.get('[data-cy="solution-code"]')
        .should('have.value', 'function solve(a, b) { return a + b + 42; }')
        .focus();
      cy.press(Cypress.Keyboard.Keys.TAB);
      cy.get('[data-cy="solution-code"]').should('not.have.focus');
      cy.contains('Pruebas visibles').should('be.visible');
      cy.contains('777113').should('not.exist');
      cy.contains('button', /^Ejecutar$/).should('not.exist');
      cy.contains('button', /^Enviar intento$/).should('not.exist');
      cy.screenshot('imp02-estudiante-editor', { capture: 'viewport' });
    });
  });
  it('IMP02-07 · Otra cuenta o cierre de sesión → borrador y contenido no se comparten', () => {
    prepare().then((f) => {
      openAs('student', solutionPath(f));
      cy.get('[data-cy="solution-code"]')
        .clear()
        .type('// borrador privado de prueba');
      cy.contains('button', /^Cerrar sesión$/).click();
      cy.location('pathname').should('eq', '/acceso');
      cy.window().then((window) =>
        expect(
          Object.keys(window.sessionStorage).filter((key) =>
            key.includes('draft'),
          ),
        ).to.have.length(0),
      );
      openAs('secondStudent', solutionPath(f));
      cy.get('[role="alert"]').should('be.visible');
      cy.get('[data-cy="solution-code"]').should('not.exist');
      cy.contains('borrador privado de prueba').should('not.exist');
      openAs('student', solutionPath(f));
      cy.get('[data-cy="solution-code"]').should(
        'not.have.value',
        '// borrador privado de prueba',
      );
      cy.get('[data-cy="solution-code"]')
        .clear()
        .type('// borrador pendiente de eliminar');
      cy.window().then((window) => {
        const storage = window.sessionStorage;
        const prototype = Object.getPrototypeOf(storage) as Storage;
        const remove = prototype.removeItem;
        cy.stub(prototype, 'removeItem')
          .callsFake(function (this: Storage, key: string) {
            if (this === storage && key.startsWith('alunza:draft:'))
              throw new Error('Controlled draft removal failure');
            return remove.call(this, key);
          })
          .as('draftRemovalFailure');
      });
      cy.contains('button', /^Cerrar sesión$/).click();
      cy.location('pathname').should('eq', '/acceso');
      cy.get('[data-cy="draft-cleanup-warning"]')
        .should('contain.text', 'Tu sesión se cerró, pero no pudimos eliminar')
        .and('contain.text', 'Cierra esta pestaña');
      signInStudentWithoutReload();
      openSolutionFromHome(f);
      cy.get('[data-cy="solution-code"]')
        .should('contain.value', 'function solve')
        .and('not.have.value', '// borrador pendiente de eliminar');
      cy.get('#draft-status').should(
        'contain.text',
        'no se confirmó su eliminación anterior',
      );
      cy.get('[data-cy="solution-code"]')
        .clear()
        .type('// solo memoria mientras falla limpieza');
      cy.get('#draft-status').should('have.attr', 'role', 'alert');
      cy.contains('button', /^Cerrar sesión$/).click();
      cy.location('pathname').should('eq', '/acceso');
      cy.get('@draftRemovalFailure').invoke('restore');
      signInStudentWithoutReload();
      cy.get('[data-cy="draft-cleanup-warning"]').should('not.exist');
      cy.window().then((window) =>
        expect(
          Object.keys(window.sessionStorage).filter((key) =>
            key.startsWith('alunza:draft:'),
          ),
        ).to.have.length(0),
      );
      openSolutionFromHome(f);
      cy.get('[data-cy="solution-code"]')
        .should('contain.value', 'function solve')
        .and('not.have.value', '// borrador pendiente de eliminar');
    });
  });
  it('IMP02-08 · Almacenamiento local falla → plantilla visible y texto conservado con aviso', () => {
    prepare().then((f) => {
      openAs('student', solutionPath(f), 'read');
      cy.get('[data-cy="solution-code"]').should(
        'contain.value',
        'function solve',
      );
      cy.get('#draft-status').should('have.attr', 'role', 'alert');
      openAs('student', solutionPath(f), 'write');
      cy.get('[data-cy="solution-code"]')
        .clear()
        .type('// conservar aunque no se guarde');
      cy.get('#draft-status').should('have.attr', 'role', 'alert');
      cy.get('[data-cy="solution-code"]').should(
        'have.value',
        '// conservar aunque no se guarde',
      );
    });
  });
  it('IMP02-09 · Cierre durante edición → acceso bloqueado y texto disponible para copiar', () => {
    prepare().then((f) => {
      openAs('student', solutionPath(f));
      cy.get('[data-cy="solution-code"]')
        .clear()
        .type('// trabajo antes del cierre');
      cy.task<{ status: number }>(
        'academic:request',
        {
          role: 'teacher',
          path: `/activities/${f.activity.id}/close`,
          options: { method: 'POST', body: {}, revision: f.activity.revision },
        },
        { log: false },
      )
        .its('status')
        .should('eq', 200);
      cy.contains('button', /^Comprobar disponibilidad$/).click();
      cy.get('[data-cy="solution-code"]').should('have.attr', 'readonly');
      cy.get('[data-cy="solution-code"]').should(
        'have.value',
        '// trabajo antes del cierre',
      );
      // A transient outage after a confirmed closure must not make it editable again.
      cy.task('foundation:apiStop', null, { log: false });
      cy.contains('button', /^Comprobar disponibilidad$/).click();
      cy.get('[role="alert"]').should(
        'contain.text',
        'No pudimos conectar con la API',
      );
      cy.get('[data-cy="solution-code"]').should('have.attr', 'readonly');
      cy.get('[data-cy="solution-code"]').should(
        'have.value',
        '// trabajo antes del cierre',
      );
      cy.task('foundation:apiStart', null, { log: false });
      cy.reload();
      cy.get('[role="alert"]').should('be.visible');
      cy.get('[data-cy="solution-code"]').should('not.exist');
    });
  });
});
