// Generated by Cypress Author on 2026-09-27 for IMP-04.01–04.03.
// Auth, API, Storage and pgvector are real LAB TEST services. Only embeddings
// use the explicitly injected deterministic test provider; this is not Azure acceptance.
import type { Session } from '@supabase/supabase-js';
import { errorResponseSchema } from '@alunza/contracts';
import type {
  AcademicClass,
  Activity,
  Course,
  Exercise,
  JoinCode,
  MaterialOperation,
  MaterialSource,
} from '@alunza/contracts';
import identityFixture from '../../fixtures/foundation/identity.json';
import { pressEnterInChrome } from './keyboard';

const organizationId = identityFixture.organizations[0]!.id;
const teacherId = identityFixture.users.find(
  (user) => user.organizationId === organizationId && user.role === 'TEACHER',
)!.id;
type Setup = {
  admin: Session;
  teacher: Session;
  student: Session;
  outsider: Session;
  classroom: AcademicClass;
  activities: Activity[];
};

function rest<T extends object>(
  session: Session,
  method: 'GET' | 'POST' | 'PUT',
  path: string,
  body?: Record<string, unknown>,
  revision?: number,
): Cypress.Chainable<T> {
  return cy
    .env(['apiBaseUrl'], { log: false })
    .then(({ apiBaseUrl }) =>
      cy.request<{ data: T }>({
        method,
        url: `${apiBaseUrl}/api/v1${path}`,
        body,
        log: false,
        headers: {
          Authorization: `Bearer ${session.access_token}`,
          'Idempotency-Key': crypto.randomUUID(),
          ...(revision ? { 'If-Match': `"${revision}"` } : {}),
        },
      }),
    )
    .then((response) => {
      expect(response.status).to.be.within(200, 299);
      return cy.wrap(response.body.data, { log: false });
    });
}
function setup(): Cypress.Chainable<Setup> {
  const suffix = crypto.randomUUID().slice(0, 8);
  const context = { activities: [] } as unknown as Setup;
  return cy
    .task<Session>('identity:login', 'ADMIN', { log: false })
    .then((session) => {
      context.admin = session;
      return cy.task<Session>('identity:login', 'TEACHER', { log: false });
    })
    .then((session) => {
      context.teacher = session;
      return cy.task<Session>('identity:login', 'STUDENT', { log: false });
    })
    .then((session) => {
      context.student = session;
      return cy.task<Session>(
        'identity:login',
        { role: 'STUDENT', academicStudent: 2 },
        { log: false },
      );
    })
    .then((session) => {
      context.outsider = session;
      return rest<Course>(
        context.admin,
        'POST',
        `/organizations/${organizationId}/courses`,
        {
          code: `MAT-${suffix}`,
          name: `Materiales ${suffix}`,
          description: 'Curso ficticio para ingestión',
          academicPeriod: '2026-2',
          startDate: '2026-08-01',
          endDate: '2026-12-31',
        },
      );
    })
    .then((course) =>
      rest<Course>(
        context.admin,
        'PUT',
        `/courses/${course.id}/teachers/${teacherId}`,
        { enabled: true },
        course.revision,
      ).then(() => course),
    )
    .then((course) =>
      rest<AcademicClass>(
        context.teacher,
        'POST',
        `/organizations/${organizationId}/classes`,
        {
          courseId: course.id,
          code: `MAT-${suffix}`,
          name: `Clase materiales ${suffix}`,
          description: 'Fixture aislado de fuentes',
          startDate: '2026-08-01',
          endDate: '2026-12-31',
        },
      ),
    )
    .then((classroom) => {
      context.classroom = classroom;
      return rest<JoinCode>(
        context.teacher,
        'POST',
        `/classes/${classroom.id}/join-codes`,
        {},
        classroom.revision,
      );
    })
    .then((join) =>
      rest(context.student, 'POST', '/class-enrollments', { code: join.code }),
    )
    .then(() =>
      rest<Exercise[]>(
        context.teacher,
        'GET',
        `/organizations/${organizationId}/exercises?limit=100`,
      ),
    )
    .then((exercises) => {
      const exercise =
        exercises.find((item) => item.state === 'ACTIVE') ?? exercises[0]!;
      function activity(title: string) {
        return rest<Activity>(
          context.teacher,
          'POST',
          `/classes/${context.classroom.id}/activities`,
          {
            title,
            instructions: 'Consulta el material oficial autorizado.',
            type: 'FORMATIVE',
            opensAt: null,
            closesAt: null,
            exercises: [
              {
                exerciseVersionId: exercise.currentVersionId,
                position: 0,
                required: true,
              },
            ],
          },
        )
          .then((draft) =>
            rest<Activity>(
              context.teacher,
              'POST',
              `/activities/${draft.id}/publish`,
              {},
              draft.revision,
            ),
          )
          .then((published) => {
            context.activities.push(published);
          });
      }
      return activity(`Material dirigido ${suffix}`).then(() =>
        activity(`Otra actividad ${suffix}`),
      );
    })
    .then(() => cy.wrap(context, { log: false }));
}
function visitAs(session: Session, path: string) {
  return cy.visit(path, {
    onBeforeLoad(window) {
      window.localStorage.setItem(
        'alunza.auth.127.0.0.1:18421',
        JSON.stringify(session),
      );
    },
  });
}
function textFile(
  contents: string,
  fileName = 'material.txt',
): Cypress.FileReference {
  return {
    contents: Cypress.Buffer.from(contents),
    fileName,
    mimeType: fileName.endsWith('.md') ? 'text/markdown' : 'text/plain',
  };
}
function upload(
  context: Setup,
  title: string,
  file: Cypress.FileReference,
  activityId?: string,
): Cypress.Chainable<MaterialSource> {
  cy.intercept('POST', `**/api/v1/classes/${context.classroom.id}/sources`).as(
    'materialUpload',
  );
  cy.contains('button', /^Cargar material$/)
    .focus()
    .should('be.focused');
  pressEnterInChrome();
  cy.get('[role="dialog"]').within(() => {
    cy.get('input[name="title"]').should('be.focused').type(title);
    if (activityId)
      cy.get('select[name="activityId"]')
        .should('be.enabled')
        .select(activityId);
    cy.get('input[name="file"]').selectFile(file);
    cy.contains('button', 'Cargar y procesar').should('be.enabled').click();
  });
  return cy
    .wait<{ data: MaterialOperation }>('@materialUpload', {
      responseTimeout: 60_000,
    })
    .then(({ response }) => {
      const failure = errorResponseSchema.safeParse(response?.body);
      const description = [
        `Carga ${title} (${activityId ? 'actividad' : 'clase'})`,
        ...(failure.success
          ? [
              `error.code=${failure.data.error.code}`,
              `requestId=${failure.data.requestId}`,
            ]
          : []),
      ].join('; ');
      expect(response?.statusCode, description).to.equal(202);
      cy.get('[role="dialog"]').should('not.exist');
      cy.contains('button', /^Cargar material$/).should('be.focused');
      return cy.wrap(
        (response!.body as { data: MaterialOperation }).data.source,
        { log: false },
      );
    });
}
function ready(title: string, version = 1, jobId?: string) {
  return cy
    .contains('[data-cy="material-card"]', title, { timeout: 90_000 })
    .within(() => {
      cy.get('[data-cy="material-availability"]', { timeout: 90_000 }).should(
        'have.text',
        'Disponible',
      );
      cy.get('[data-cy="material-active-version"]', { timeout: 90_000 }).should(
        'contain.text',
        `Versión disponible: ${version}`,
      );
      cy.get('[data-cy="material-processing"]', { timeout: 90_000 }).should(
        ($processing) => {
          expect($processing).to.contain.text('Completado');
          if (jobId) expect($processing).to.have.attr('data-job-id', jobId);
        },
      );
    });
}

describe('Materiales oficiales de clase y actividad', () => {
  beforeEach(() => {
    cy.task('materials:fault/clear', null, { log: false });
  });
  afterEach(() => {
    cy.task('materials:fault/clear', null, { log: false });
  });
  it('IMP04-01 profesor carga TXT → alumno inscrito lo consulta y una clase ajena no lo obtiene', () => {
    setup().then((context) => {
      const suffix = crypto.randomUUID().slice(0, 8);
      const title = `Funciones ${suffix}`;
      const fileName = `funciones-${suffix}.txt`;
      const text =
        'Una función recibe parámetros y retorna un resultado. Console.log muestra un valor, pero no lo retorna.';
      visitAs(context.teacher, `/clases/${context.classroom.id}`);
      upload(context, title, textFile(text, fileName)).then((source) => {
        ready(title);
        cy.reload();
        ready(title);
        cy.contains('[data-cy="material-card"]', title).within(() => {
          cy.contains('button', 'Consultar versiones').click();
          cy.get('[data-cy="material-history"]').within(() => {
            cy.contains('button', 'Consultar fragmentos').click();
            cy.get('[data-cy="material-chunk-text"]').should('have.text', text);
            cy.get('[data-cy="material-chunk-locator"]').should(
              'have.text',
              'Líneas 1–1',
            );
          });
        });
        rest<MaterialSource>(
          context.teacher,
          'GET',
          `/sources/${source.id}`,
        ).then((current) => {
          const content = `/api/v1/sources/${source.id}/versions/${current.activeVersion!.id}/content`;
          cy.intercept('GET', `**${content}`).as('materialDownload');
          cy.env(['apiBaseUrl'], { log: false }).then(({ apiBaseUrl }) => {
            cy.request({
              url: `${apiBaseUrl}${content}`,
              headers: {
                Authorization: `Bearer ${context.student.access_token}`,
              },
              log: false,
            }).then((response) => {
              expect(response.status).to.equal(200);
              expect(response.body).to.equal(text);
            });
            cy.request({
              url: `${apiBaseUrl}${content}`,
              headers: {
                Authorization: `Bearer ${context.outsider.access_token}`,
              },
              failOnStatusCode: false,
              log: false,
            })
              .its('status')
              .should('eq', 404);
            cy.request({
              url: `${apiBaseUrl}/api/v1/classes/${context.classroom.id}/sources`,
              headers: {
                Authorization: `Bearer ${context.outsider.access_token}`,
              },
              failOnStatusCode: false,
              log: false,
            })
              .its('status')
              .should('eq', 404);
          });
        });
        visitAs(context.student, `/clases/${context.classroom.id}`);
        cy.contains('[data-cy="material-card"]', title).within(() => {
          cy.get('[data-cy="material-availability"]').should(
            'have.text',
            'Disponible',
          );
          cy.contains('button', 'Descargar versión 1')
            .should('be.visible')
            .click();
          cy.contains('button', 'Subir nueva versión').should('not.exist');
          cy.contains('button', 'Archivar material').should('not.exist');
        });
        cy.wait('@materialDownload', { responseTimeout: 45_000 }).then(
          ({ response }) => {
            expect(response?.statusCode).to.equal(200);
            expect(response?.headers['cache-control']).to.contain('no-store');
            expect(response?.headers['content-disposition']).to.contain(
              'attachment',
            );
            expect(response?.body).to.equal(text);
          },
        );
        cy.readFile(
          `${Cypress.config('downloadsFolder')}/${fileName}`,
          'utf8',
        ).should('eq', text);
      });
    });
  });

  it('IMP04-02 profesor carga PDF y Markdown → conserva el ámbito de actividad y rechaza un formato inválido', () => {
    setup().then((context) => {
      const pdfTitle = `PDF ${crypto.randomUUID().slice(0, 8)}`;
      const mdTitle = `Guía Markdown ${crypto.randomUUID().slice(0, 8)}`;
      visitAs(context.teacher, `/clases/${context.classroom.id}`);
      upload(
        context,
        pdfTitle,
        'fixtures/demo/materials/a1-funciones.pdf',
      ).then(() => ready(pdfTitle));
      upload(
        context,
        mdTitle,
        textFile(
          '# Retorno\n\nRevisa la diferencia entre mostrar un valor y retornarlo.',
          'guia.md',
        ),
        context.activities[0]!.id,
      ).then(() => ready(mdTitle));
      cy.contains('button', /^Cargar material$/).click();
      cy.get('[role="dialog"]').within(() => {
        cy.get('input[name="title"]').type('Archivo no permitido');
        cy.get('input[name="file"]').selectFile({
          contents: Cypress.Buffer.from([0, 1, 2, 3]),
          fileName: 'archivo.exe',
          mimeType: 'application/octet-stream',
        });
        cy.contains('button', 'Cargar y procesar').should('be.enabled').click();
        cy.contains('Utiliza un PDF con texto, TXT o Markdown.').should(
          'be.visible',
        );
        cy.get('input[name="title"]').should(
          'have.value',
          'Archivo no permitido',
        );
        cy.get('input[name="title"]').focus();
        cy.press(Cypress.Keyboard.Keys.ESC);
      });
      cy.get('[role="dialog"]').should('not.exist');
      cy.contains('button', /^Cargar material$/).should('be.focused');
      visitAs(context.student, `/actividades/${context.activities[0]!.id}`);
      cy.contains('[data-cy="material-card"]', pdfTitle).should('be.visible');
      cy.contains('[data-cy="material-card"]', mdTitle).should('be.visible');
      visitAs(context.student, `/actividades/${context.activities[1]!.id}`);
      cy.contains('[data-cy="material-card"]', pdfTitle).should('be.visible');
      cy.contains('[data-cy="material-card"]', mdTitle).should('not.exist');
    });
  });

  it('IMP04-03 reemplazo fallido → conserva versión válida; nueva versión y gobierno mantienen la historia', () => {
    setup().then((context) => {
      const title = `Material versionado ${crypto.randomUUID().slice(0, 8)}`;
      visitAs(context.teacher, `/clases/${context.classroom.id}`);
      upload(
        context,
        title,
        textFile(
          'Los parámetros representan entradas; return entrega el resultado de la función.',
        ),
      ).then((source) => {
        ready(title);
        const failedText = 'Fallo permanente del proveedor doble de pruebas.';
        cy.task(
          'materials:fault/set',
          { text: failedText, scenario: 'permanent' },
          { log: false },
        );
        cy.contains('[data-cy="material-card"]', title)
          .contains('button', 'Subir nueva versión')
          .click();
        cy.get('[role="dialog"]').within(() => {
          cy.get('input[name="file"]').selectFile(textFile(failedText));
          cy.contains('button', 'Cargar y procesar').click();
        });
        cy.contains('[data-cy="material-card"]', title).within(() => {
          cy.get('[data-cy="material-processing"]', { timeout: 90_000 }).should(
            'contain.text',
            'Fallido',
          );
          cy.get('[data-cy="material-active-version"]').should(
            'contain.text',
            'Versión disponible: 1',
          );
          cy.get('[data-cy="material-availability"]').should(
            'have.text',
            'Disponible',
          );
          cy.contains('button', 'Reintentar procesamiento').should(
            'be.visible',
          );
          cy.contains('button', 'Subir nueva versión').click();
        });
        cy.get('[role="dialog"]').within(() => {
          cy.get('input[name="file"]').selectFile(
            textFile(
              'Versión corregida. Comprueba cada rama y retorna un valor para cada entrada.',
            ),
          );
          cy.contains('button', 'Cargar y procesar').click();
        });
        ready(title, 3);
        cy.contains('[data-cy="material-card"]', title)
          .contains('button', 'Consultar versiones')
          .click();
        cy.get('[data-cy="material-history"]')
          .should('contain.text', 'Versión 1')
          .and('contain.text', 'Versión 2')
          .and('contain.text', 'Versión 3');
        visitAs(context.admin, `/clases/${context.classroom.id}`);
        cy.intercept('POST', `**/api/v1/sources/${source.id}/reindex`).as(
          'materialReindex',
        );
        cy.contains('[data-cy="material-card"]', title)
          .contains('button', 'Reindexar material')
          .click();
        cy.get('[role="dialog"]').contains('button', 'Confirmar').click();
        cy.wait('@materialReindex').then(({ response }) => {
          expect(response?.statusCode).to.equal(202);
          const operation = (response!.body as { data: MaterialOperation })
            .data;
          expect(operation.job.sourceId).to.equal(source.id);
          // The previous generation remains available during reindexing. Wait
          // for this admitted job, not its predecessor's completed label.
          ready(title, 3, operation.job.id);
        });
        cy.contains('[data-cy="material-card"]', title)
          .contains('button', 'Ocultar material')
          .click();
        cy.get('[role="dialog"]').contains('button', 'Confirmar').click();
        cy.contains('[data-cy="material-card"]', title).should(
          'contain.text',
          'Oculto para estudiantes',
        );
        visitAs(context.student, `/clases/${context.classroom.id}`);
        cy.contains('No hay materiales disponibles en este ámbito.').should(
          'be.visible',
        );
        cy.contains('[data-cy="material-card"]', title).should('not.exist');
        visitAs(context.admin, `/clases/${context.classroom.id}`);
        cy.intercept('POST', `**/api/v1/sources/${source.id}/archive`).as(
          'materialArchive',
        );
        cy.contains('[data-cy="material-card"]', title)
          .contains('button', 'Archivar material')
          .click();
        cy.get('[role="dialog"]').within(() => {
          cy.get('input[name="reason"]').type(
            'Retiro del material ficticio de prueba',
          );
          cy.contains('button', 'Guardar').click();
        });
        cy.wait('@materialArchive').then(({ response }) => {
          expect(response?.statusCode).to.equal(200);
          expect(
            (response!.body as { data: MaterialSource }).data.state,
          ).to.equal('ARCHIVED');
        });
        cy.contains('[data-cy="material-card"]', title).should(
          'contain.text',
          'Archivado',
        );
        rest<MaterialSource>(
          context.admin,
          'GET',
          `/sources/${source.id}`,
        ).then((archived) => {
          expect(archived.state).to.equal('ARCHIVED');
          expect(archived.activeVersion?.version).to.equal(3);
        });
      });
    });
  });
});
