// Generated by Cypress Author on 2026-09-26 for IMP-03.
import type { Session } from '@supabase/supabase-js';
import type {
  Activity,
  AcademicClass,
  Concept,
  Course,
  Exercise,
  JoinCode,
} from '@alunza/contracts';
import identityFixture from '../../fixtures/foundation/identity.json';

const organizationId = identityFixture.organizations[0]!.id;
const teacherId = identityFixture.users.find(
  (user) => user.organizationId === organizationId && user.role === 'TEACHER',
)!.id;
const correct = 'module.exports.solve = (a, b) => a + b;';
type Setup = {
  admin: Session;
  teacher: Session;
  student: Session;
  course: Course;
  classroom: AcademicClass;
  concept: Concept;
  exercise: Exercise;
  activity: Activity;
};

function rest<T extends object>(
  session: Session,
  method: 'POST' | 'PUT',
  path: string,
  body: Record<string, unknown>,
  revision?: number,
): Cypress.Chainable<T> {
  return cy
    .env(['apiBaseUrl'], { log: false })
    .then(({ apiBaseUrl }) =>
      cy.request<{ data: T }>({
        method,
        url: `${apiBaseUrl}/api/v1${path}`,
        body,
        log: false,
        headers: {
          Authorization: `Bearer ${session.access_token}`,
          'Idempotency-Key': crypto.randomUUID(),
          ...(revision ? { 'If-Match': `"${revision}"` } : {}),
        },
      }),
    )
    .then((response) => {
      expect(response.status).to.be.within(200, 299);
      return cy.wrap(response.body.data, { log: false });
    });
}
function setup(): Cypress.Chainable<Setup> {
  const suffix = crypto.randomUUID().slice(0, 8);
  const context = {} as Setup;
  return cy
    .task<Session>('identity:login', 'ADMIN', { log: false })
    .then((session) => {
      context.admin = session;
      return cy.task<Session>('identity:login', 'TEACHER', { log: false });
    })
    .then((session) => {
      context.teacher = session;
      return cy.task<Session>('identity:login', 'STUDENT', { log: false });
    })
    .then((session) => {
      context.student = session;
      return rest<Course>(
        context.admin,
        'POST',
        `/organizations/${organizationId}/courses`,
        {
          code: `RUN-${suffix}`,
          name: `Curso RUN ${suffix}`,
          description: 'Fixture adicional de práctica',
          academicPeriod: '2026-2',
          startDate: '2026-08-01',
          endDate: '2026-12-31',
        },
      );
    })
    .then((course) => {
      context.course = course;
      return rest<Course>(
        context.admin,
        'PUT',
        `/courses/${course.id}/teachers/${teacherId}`,
        { enabled: true },
        course.revision,
      );
    })
    .then(() =>
      rest<Concept>(
        context.admin,
        'POST',
        `/organizations/${organizationId}/concepts`,
        {
          name: `Suma RUN ${suffix}`,
          description: 'Operaciones numéricas',
          parentId: null,
        },
      ),
    )
    .then((concept) => {
      context.concept = concept;
      return rest<AcademicClass>(
        context.teacher,
        'POST',
        `/organizations/${organizationId}/classes`,
        {
          courseId: context.course.id,
          code: `RUN-${suffix}`,
          name: `Clase RUN ${suffix}`,
          description: 'Fixture adicional',
          startDate: '2026-08-01',
          endDate: '2026-12-31',
        },
      );
    })
    .then((classroom) => {
      context.classroom = classroom;
      return rest<Exercise>(
        context.teacher,
        'POST',
        `/organizations/${organizationId}/exercises`,
        {
          title: `Sumar RUN ${suffix}`,
          statement: 'Devuelve la suma de los dos argumentos.',
          starterCode: 'module.exports.solve = (a, b) => 0;',
          language: 'javascript',
          entrypoint: 'solve',
          difficulty: 'BEGINNER',
          conceptVersionIds: [context.concept.currentVersionId],
          tests: [
            {
              id: 'visible-run-suma',
              visibility: 'visible',
              args: [2, 3],
              expected: 5,
            },
            {
              id: 'hidden-run-sentinel',
              visibility: 'hidden',
              args: [98761, 34529],
              expected: 133290,
            },
          ],
          executionLimits: {
            memoryBytes: 134217728,
            runtimeMs: 3000,
            outputBytes: 65536,
          },
        },
      );
    })
    .then((exercise) => {
      context.exercise = exercise;
      return rest<Activity>(
        context.teacher,
        'POST',
        `/classes/${context.classroom.id}/activities`,
        {
          title: `Práctica RUN ${suffix}`,
          instructions: 'Ejecuta tu solución con las pruebas visibles.',
          type: 'FORMATIVE',
          opensAt: null,
          closesAt: null,
          exercises: [
            {
              exerciseVersionId: exercise.currentVersionId,
              position: 0,
              required: true,
            },
          ],
        },
      );
    })
    .then((activity) =>
      rest<Activity>(
        context.teacher,
        'POST',
        `/activities/${activity.id}/publish`,
        {},
        activity.revision,
      ),
    )
    .then((activity) => {
      context.activity = activity;
      return rest<JoinCode>(
        context.teacher,
        'POST',
        `/classes/${context.classroom.id}/join-codes`,
        {},
        context.classroom.revision,
      );
    })
    .then((joinCode) =>
      rest(context.student, 'POST', '/class-enrollments', {
        code: joinCode.code,
      }),
    )
    .then(() => cy.wrap(context, { log: false }));
}
function path(context: Setup) {
  return `/actividades/${context.activity.id}/ejercicios/${context.activity.exercises[0]!.id}`;
}
function endpoint(context: Setup) {
  return `/api/v1/activities/${context.activity.id}/exercises/${context.activity.exercises[0]!.id}/executions`;
}
function visitAs(
  session: Session,
  url: string,
  beforeLoad?: (window: Cypress.AUTWindow) => void,
) {
  return cy.visit(url, {
    onBeforeLoad(window) {
      window.localStorage.setItem(
        'alunza.auth.127.0.0.1:18421',
        JSON.stringify(session),
      );
      beforeLoad?.(window);
    },
  });
}
function writeCode(code: string) {
  // Focus first: entering the browser can trigger access revalidation. Wait for
  // its readonly guard before clearing, then query the controlled input again.
  cy.get('[data-cy="student-code"]')
    .should(($editor) => expect($editor).not.to.have.attr('readonly'))
    .click();
  cy.get('[data-cy="student-code"]')
    .should(($editor) => expect($editor).not.to.have.attr('readonly'))
    .clear();
  cy.get('[data-cy="student-code"]')
    .should('have.value', '')
    .type(code, { parseSpecialCharSequences: false, delay: 0 });
  cy.get('[data-cy="student-code"]').should('have.value', code);
}

function pressEnterInChrome() {
  // Cypress 16's native Enter omits the character event; its type('{enter}')
  // emits a non-bubbling click, which cannot reach React's delegated listener.
  // Supply the complete native CDP keystroke in this Chrome-only lab harness.
  // https://chromedevtools.github.io/devtools-protocol/tot/Input/#method-dispatchKeyEvent
  cy.then(() =>
    Cypress.automation('remote:debugger:protocol', {
      command: 'Input.dispatchKeyEvent',
      params: {
        type: 'keyDown',
        key: 'Enter',
        code: 'Enter',
        text: '\r',
        unmodifiedText: '\r',
        windowsVirtualKeyCode: 13,
        nativeVirtualKeyCode: 13,
      },
    }),
  );
  cy.then(() =>
    Cypress.automation('remote:debugger:protocol', {
      command: 'Input.dispatchKeyEvent',
      params: {
        type: 'keyUp',
        key: 'Enter',
        code: 'Enter',
        windowsVirtualKeyCode: 13,
        nativeVirtualKeyCode: 13,
      },
    }),
  );
}

function renewSession() {
  // Expire only the SDK's local scheduling hint. The unmodified refresh token
  // is exchanged by the real browser Auth client against the real service.
  cy.intercept('POST', '**/auth/v1/token?grant_type=refresh_token').as(
    'tokenRefresh',
  );
  cy.intercept('GET', '**/api/v1/me', (request) =>
    request.continue((response) => {
      response.setDelay(1000);
    }),
  ).as('renewedIdentity');
  cy.window({ log: false }).then((window) => {
    expect(window.document.visibilityState).to.equal('visible');
    const storageKey = 'alunza.auth.127.0.0.1:18421';
    const session = JSON.parse(window.localStorage.getItem(storageKey)!);
    window.localStorage.setItem(
      storageKey,
      JSON.stringify({ ...session, expires_at: 0 }),
    );
    window.dispatchEvent(new window.Event('visibilitychange'));
  });
  cy.wait('@tokenRefresh', { log: false })
    .its('response.statusCode', { log: false })
    .should('equal', 200);
  cy.get('[data-cy="student-code"]').should('not.be.visible');
  cy.wait('@renewedIdentity', { log: false })
    .its('response.statusCode', { log: false })
    .should('equal', 200);
  cy.get('[data-cy="student-code"]')
    .should('be.visible')
    .and('not.have.attr', 'readonly');
}

describe('IMP-03 · RUN con API y Docker reales', () => {
  beforeEach(() => setup().as('practice'));

  it('IMP03-01 · Ejecutar con teclado y editar durante la espera → muestra resultado temporal y conserva el borrador nuevo', () => {
    cy.get<Setup>('@practice').then((context) => {
      // Only delay delivery of the real response to exercise in-flight editing.
      cy.intercept('POST', `**${endpoint(context)}`, (request) =>
        request.continue((response) => {
          response.setDelay(1000);
        }),
      ).as('run');
      visitAs(context.student, path(context));
      const source =
        'module.exports.solve = (a, b) => { console.log("<b>consola segura</b>"); return a + b; };';
      writeCode(source);
      cy.get('[data-cy="student-code"]').should('have.focus');
      cy.press(Cypress.Keyboard.Keys.TAB);
      const activationEvents: {
        type: string;
        trusted: boolean;
        bubbles: boolean;
      }[] = [];
      cy.get('[data-cy="run-code"]')
        .should('have.focus')
        .and('be.enabled')
        .then(($button) => {
          for (const type of ['keydown', 'keypress'])
            $button[0]!.addEventListener(type, (event) => {
              activationEvents.push({
                type: `${type}:${(event as KeyboardEvent).key}`,
                trusted: event.isTrusted,
                bubbles: event.bubbles,
              });
            });
          $button[0]!.addEventListener('click', (event) =>
            activationEvents.push({
              type: 'click',
              trusted: event.isTrusted,
              bubbles: event.bubbles,
            }),
          );
        });
      pressEnterInChrome();
      cy.then(() => {
        expect(activationEvents.map((event) => event.type)).to.deep.equal([
          'keydown:Enter',
          'keypress:Enter',
          'click',
        ]);
        expect(
          activationEvents.every((event) => event.trusted && event.bubbles),
        ).to.equal(true);
      });
      cy.get('[data-cy="run-code"]').should('be.disabled');
      cy.get('[data-cy="run-status"]').should('contain.text', 'Ejecutando');
      cy.get('[data-cy="student-code"]').should('not.have.attr', 'readonly');
      writeCode('// borrador posterior a la ejecución');
      cy.wait('@run', { responseTimeout: 45_000 }).then(
        ({ request, response }) => {
          expect(response!.statusCode).to.equal(201);
          expect(request.body.code).to.equal(source);
          expect(response!.body.data.mode).to.equal('RUN');
          expect(response!.body.data.technicalResult.visibleTotal).to.equal(1);
          expect(JSON.stringify(response!.body)).not.to.contain(
            'hidden-run-sentinel',
          );
          expect(JSON.stringify(response!.body)).not.to.contain('98761');
        },
      );
      cy.get('[data-cy="run-diagnosis"]').should('contain.text', 'SUCCESS');
      cy.get('[data-cy="stale-run"]').should('be.visible');
      cy.get('[data-cy="practice-result"]')
        .should('contain.text', 'Pruebas visibles superadas: 1/1')
        .and('contain.text', '<b>consola segura</b>');
      cy.get('[data-cy="practice-result"] b').should('not.exist');
      cy.get('[data-cy="run-visible-test"]').should('have.length', 1);
      cy.contains('button', 'Enviar intento').should('be.enabled');
      cy.reload();
      cy.get('[data-cy="student-code"]').should(
        'have.value',
        '// borrador posterior a la ejecución',
      );
      cy.get('[data-cy="practice-result"]').should('not.exist');
    });
  });

  it('IMP03-02 · Ejecutar solución incorrecta, sintaxis inválida y bucle infinito → informa cada diagnóstico sin perder código', () => {
    cy.get<Setup>('@practice').then((context) => {
      const keys = new Set<string>();
      cy.intercept('POST', `**${endpoint(context)}`).as('run');
      visitAs(context.student, path(context));
      for (const [code, diagnosis] of [
        ['module.exports.solve = () => 0;', 'FAILED_TEST'],
        ['module.exports.solve = ( => ;', 'SYNTAX_ERROR'],
        ['module.exports.solve = () => { while (true) {} };', 'TIMEOUT'],
      ]) {
        writeCode(code!);
        cy.get('[data-cy="run-code"]').should('be.enabled').click();
        cy.wait('@run', { responseTimeout: 45_000 }).then(
          ({ request, response }) => {
            expect(response!.statusCode).to.equal(201);
            expect(response!.body.data.technicalResult.diagnosisCode).to.equal(
              diagnosis,
            );
            const key = String(request.headers['idempotency-key']);
            expect(keys.has(key)).to.equal(false);
            keys.add(key);
          },
        );
        cy.get('[data-cy="run-diagnosis"]').should('contain.text', diagnosis);
        cy.get('[data-cy="student-code"]').should('have.value', code);
      }
    });
  });

  it('IMP03-03 · Renovar la sesión, perder una respuesta y cerrar la actividad → conserva el borrador y recupera la ejecución original', () => {
    cy.get<Setup>('@practice').then((context) => {
      let loseResponse: (() => void) | undefined;
      let requestSignal: AbortSignal | null | undefined;
      const observed: {
        key: string | null;
        body: string;
        executionId: string;
      }[] = [];
      visitAs(context.student, path(context), (window) => {
        const original = window.fetch.bind(window);
        const setItem = window.Storage.prototype.setItem;
        // Keep Auth storage working while proving the draft survives in memory.
        window.Storage.prototype.setItem = function (key, value) {
          if (key.startsWith('alunza.exercise-draft.v1:'))
            throw new window.DOMException('Draft storage unavailable');
          return setItem.call(this, key, value);
        };
        // Real API/Docker finishes first; only the browser delivery fails once.
        window.fetch = (input, init) =>
          original(input, init).then(async (response) => {
            if (
              String(input).endsWith(endpoint(context)) &&
              init?.method === 'POST' &&
              response.status === 201
            ) {
              const body = await response.clone().json();
              observed.push({
                key: new Headers(init.headers).get('Idempotency-Key'),
                body: String(init.body),
                executionId: body.data.executionId,
              });
              if (observed.length === 1) {
                requestSignal = init.signal;
                return new Promise<Response>((_resolve, reject) => {
                  loseResponse = () =>
                    reject(
                      new TypeError(
                        'Simulated lost response after confirmed execution',
                      ),
                    );
                });
              }
            }
            return response;
          });
      });
      writeCode(correct);
      cy.get('[data-cy="run-code"]').click();
      cy.wrap(null, { timeout: 45_000, log: false }).should(() => {
        expect(loseResponse, 'respuesta real lista para entregar').to.be.a(
          'function',
        );
      });
      writeCode('// conservar borrador nuevo durante la recuperación');
      cy.get('#draft-status').should('contain.text', 'No se pudo guardar');
      renewSession();
      cy.get('[data-cy="student-code"]').should(
        'have.value',
        '// conservar borrador nuevo durante la recuperación',
      );
      cy.get('[data-cy="run-status"]').should('contain.text', 'Ejecutando');
      cy.get('[data-cy="run-code"]').should('be.disabled');
      cy.then(() => {
        expect(requestSignal?.aborted, 'RUN conservado tras renovar').to.equal(
          false,
        );
        loseResponse!();
      });
      cy.get('[data-cy="recover-run"]', { timeout: 45_000 }).should(
        'be.enabled',
      );
      cy.get('[data-cy="run-code"]').should('be.disabled');
      renewSession();
      cy.get('[data-cy="recover-run"]').should('be.enabled');
      cy.get('[data-cy="run-code"]').should('be.disabled');
      rest<Activity>(
        context.teacher,
        'POST',
        `/activities/${context.activity.id}/close`,
        {},
        context.activity.revision,
      );
      cy.contains('button', 'Actualizar disponibilidad').click();
      cy.get('[data-cy="student-code"]').should('have.attr', 'readonly');
      cy.get('[data-cy="recover-run"]').should('be.enabled').click();
      cy.get('[data-cy="run-diagnosis"]', { timeout: 45_000 }).should(
        'contain.text',
        'SUCCESS',
      );
      cy.get('[data-cy="stale-run"]').should('be.visible');
      cy.get('[data-cy="student-code"]').should(
        'have.value',
        '// conservar borrador nuevo durante la recuperación',
      );
      cy.get('[data-cy="run-code"]').should('be.disabled');
      cy.then(() => {
        expect(observed).to.have.length(2);
        expect(observed[0]!.key).to.be.a('string').and.not.equal('');
        expect(observed[1]).to.deep.equal(observed[0]);
      });
    });
  });

  it('IMP03-04 · Acceso no autorizado o disponibilidad sin verificar → bloquea la ejecución y preserva el borrador autorizado', () => {
    cy.get<Setup>('@practice').then((context) => {
      visitAs(context.student, path(context));
      writeCode('// borrador privado conservado');
      cy.intercept(
        {
          method: 'GET',
          url: `**${endpoint(context).replace('/executions', '')}`,
          times: 1,
        },
        { forceNetworkError: true },
      ).as('unavailable');
      cy.contains('button', 'Actualizar disponibilidad').click();
      cy.wait('@unavailable');
      cy.get('[data-cy="run-code"]').should('be.disabled');
      cy.get('[data-cy="student-code"]').should(
        'have.value',
        '// borrador privado conservado',
      );
      cy.contains('button', 'Actualizar disponibilidad').click();
      cy.get('[data-cy="run-code"]').should('be.enabled');
      visitAs(context.admin, path(context));
      cy.get('[role="alert"]').should('be.visible');
      cy.get('[data-cy="student-code"]').should('not.exist');
      cy.get('[data-cy="run-code"]').should('not.exist');
      cy.env(['apiBaseUrl'], { log: false })
        .then(({ apiBaseUrl }) =>
          cy.request({
            method: 'POST',
            url: `${apiBaseUrl}${endpoint(context)}`,
            log: false,
            failOnStatusCode: false,
            headers: {
              Authorization: `Bearer ${context.admin.access_token}`,
              'Idempotency-Key': crypto.randomUUID(),
            },
            body: {
              code: correct,
              exerciseVersionId: context.exercise.currentVersionId,
            },
          }),
        )
        .then((response) => {
          expect([403, 404]).to.contain(response.status);
          expect(JSON.stringify(response.body)).not.to.contain(
            'hidden-run-sentinel',
          );
        });
    });
  });

  it('IMP03-05 · Cambiar de cuenta durante RUN → descarta la respuesta tardía y no recupera resultados al volver o recargar', () => {
    cy.get<Setup>('@practice').then((context) => {
      let releaseResponse: (() => void) | undefined;
      let requestSignal: AbortSignal | null | undefined;
      let diagnosis: string | undefined;
      const source =
        'module.exports.solve = (a, b) => { console.log("resultado privado de RUN"); return a + b; };';
      visitAs(context.student, path(context), (window) => {
        const original = window.fetch.bind(window);
        // Hold delivery only after the real API/Docker response has completed.
        // Resolve it after the account switch, even if the UI aborted its signal,
        // to verify that a late callback cannot repopulate the next context.
        window.fetch = (input, init) =>
          original(input, init).then(async (response) => {
            if (
              String(input).endsWith(endpoint(context)) &&
              init?.method === 'POST' &&
              response.status === 201
            ) {
              requestSignal = init.signal;
              diagnosis = (await response.clone().json()).data.technicalResult
                .diagnosisCode;
              return new Promise<Response>((resolve) => {
                releaseResponse = () => resolve(response);
              });
            }
            return response;
          });
      });
      writeCode(source);
      cy.get('[data-cy="run-code"]').click();
      cy.wrap(null, { timeout: 45_000, log: false }).should(() => {
        expect(releaseResponse, 'respuesta real lista para entregar').to.be.a(
          'function',
        );
        expect(diagnosis).to.equal('SUCCESS');
      });
      cy.get('[data-cy="run-status"]').should('contain.text', 'Ejecutando');
      cy.get('[data-cy="run-code"]').should('be.disabled');
      cy.contains('button', /^Cerrar sesión$/).click();
      cy.location('pathname').should('equal', '/acceso');
      cy.wrap(null, { log: false }).should(() => {
        expect(
          requestSignal?.aborted,
          'solicitud de la cuenta anterior abortada',
        ).to.equal(true);
      });
      const admin = identityFixture.users.find(
        (user) =>
          user.organizationId === organizationId && user.role === 'ADMIN',
      )!;
      // Stay in the same browser document while changing the session.
      cy.get('#email').type(admin.email, { log: false });
      cy.env(['fixturePassword'], { log: false }).then(({ fixturePassword }) =>
        cy.get('#password').type(String(fixturePassword), {
          log: false,
          parseSpecialCharSequences: false,
        }),
      );
      cy.contains('button', /^Iniciar sesión$/).click();
      cy.location('pathname').should('equal', '/inicio');
      cy.then(() => releaseResponse!());
      cy.get('[data-cy="practice-result"]').should('not.exist');
      cy.get('[data-cy="recover-run"]').should('not.exist');
      cy.contains('resultado privado de RUN').should('not.exist');
      cy.visit(path(context));
      cy.get('[role="alert"]').should('be.visible');
      cy.get('[data-cy="practice-result"]').should('not.exist');
      cy.get('[data-cy="student-code"]').should('not.exist');
      cy.task<Session>('identity:login', 'STUDENT', { log: false }).then(
        (session) => visitAs(session, path(context)),
      );
      cy.get('[data-cy="student-code"]').should('have.value', source);
      cy.get('[data-cy="practice-result"]').should('not.exist');
      cy.get('[data-cy="recover-run"]').should('not.exist');
      cy.get('[data-cy="run-code"]').should('be.enabled');
      cy.reload();
      cy.get('[data-cy="student-code"]').should('have.value', source);
      cy.get('[data-cy="practice-result"]').should('not.exist');
      cy.get('[data-cy="recover-run"]').should('not.exist');
    });
  });
});
