// Generated by Cypress Author on 2026-09-26 for IMP-03.
import type { Session } from '@supabase/supabase-js';
import type {
  Activity,
  AcademicClass,
  Concept,
  Course,
  Exercise,
  JoinCode,
} from '@alunza/contracts';
import identityFixture from '../../fixtures/foundation/identity.json';

const organizationId = identityFixture.organizations[0]!.id;
const teacherId = identityFixture.users.find(
  (user) => user.organizationId === organizationId && user.role === 'TEACHER',
)!.id;
const correct = 'module.exports.solve = (a, b) => a + b;';
type Setup = {
  admin: Session;
  teacher: Session;
  student: Session;
  studentFixture: { role: 'STUDENT'; academicStudent: number };
  course: Course;
  classroom: AcademicClass;
  concept: Concept;
  exercise: Exercise;
  activity: Activity;
};

function rest<T extends object>(
  session: Session,
  method: 'POST' | 'PUT',
  path: string,
  body: Record<string, unknown>,
  revision?: number,
): Cypress.Chainable<T> {
  return cy
    .env(['apiBaseUrl'], { log: false })
    .then(({ apiBaseUrl }) =>
      cy.request<{ data: T }>({
        method,
        url: `${apiBaseUrl}/api/v1${path}`,
        body,
        log: false,
        headers: {
          Authorization: `Bearer ${session.access_token}`,
          'Idempotency-Key': crypto.randomUUID(),
          ...(revision ? { 'If-Match': `"${revision}"` } : {}),
        },
      }),
    )
    .then((response) => {
      expect(response.status).to.be.within(200, 299);
      return cy.wrap(response.body.data, { log: false });
    });
}
function setup(academicStudent: number): Cypress.Chainable<Setup> {
  const suffix = crypto.randomUUID().slice(0, 8);
  const context = {} as Setup;
  context.studentFixture = { role: 'STUDENT', academicStudent };
  return cy
    .task<Session>('identity:login', 'ADMIN', { log: false })
    .then((session) => {
      context.admin = session;
      return cy.task<Session>('identity:login', 'TEACHER', { log: false });
    })
    .then((session) => {
      context.teacher = session;
      return cy.task<Session>('identity:login', context.studentFixture, {
        log: false,
      });
    })
    .then((session) => {
      context.student = session;
      return rest<Course>(
        context.admin,
        'POST',
        `/organizations/${organizationId}/courses`,
        {
          code: `SUBMIT-${suffix}`,
          name: `Curso SUBMIT ${suffix}`,
          description: 'Fixture adicional de práctica',
          academicPeriod: '2026-2',
          startDate: '2026-08-01',
          endDate: '2026-12-31',
        },
      );
    })
    .then((course) => {
      context.course = course;
      return rest<Course>(
        context.admin,
        'PUT',
        `/courses/${course.id}/teachers/${teacherId}`,
        { enabled: true },
        course.revision,
      );
    })
    .then(() =>
      rest<Concept>(
        context.admin,
        'POST',
        `/organizations/${organizationId}/concepts`,
        {
          name: `Suma SUBMIT ${suffix}`,
          description: 'Operaciones numéricas',
          parentId: null,
        },
      ),
    )
    .then((concept) => {
      context.concept = concept;
      return rest<AcademicClass>(
        context.teacher,
        'POST',
        `/organizations/${organizationId}/classes`,
        {
          courseId: context.course.id,
          code: `SUBMIT-${suffix}`,
          name: `Clase SUBMIT ${suffix}`,
          description: 'Fixture adicional',
          startDate: '2026-08-01',
          endDate: '2026-12-31',
        },
      );
    })
    .then((classroom) => {
      context.classroom = classroom;
      return rest<Exercise>(
        context.teacher,
        'POST',
        `/organizations/${organizationId}/exercises`,
        {
          title: `Sumar SUBMIT ${suffix}`,
          statement: 'Devuelve la suma de los dos argumentos.',
          starterCode: 'module.exports.solve = (a, b) => 0;',
          language: 'javascript',
          entrypoint: 'solve',
          difficulty: 'BEGINNER',
          conceptVersionIds: [context.concept.currentVersionId],
          tests: [
            {
              id: 'visible-submit-suma',
              visibility: 'visible',
              args: [2, 3],
              expected: 5,
            },
            {
              id: 'hidden-submit-sentinel',
              visibility: 'hidden',
              args: [98761, 34529],
              expected: 133290,
            },
          ],
          executionLimits: {
            memoryBytes: 134217728,
            runtimeMs: 3000,
            outputBytes: 65536,
          },
        },
      );
    })
    .then((exercise) => {
      context.exercise = exercise;
      return rest<Activity>(
        context.teacher,
        'POST',
        `/classes/${context.classroom.id}/activities`,
        {
          title: `Práctica SUBMIT ${suffix}`,
          instructions: 'Ejecuta tu solución con las pruebas visibles.',
          type: 'FORMATIVE',
          opensAt: null,
          closesAt: null,
          exercises: [
            {
              exerciseVersionId: exercise.currentVersionId,
              position: 0,
              required: true,
            },
          ],
        },
      );
    })
    .then((activity) =>
      rest<Activity>(
        context.teacher,
        'POST',
        `/activities/${activity.id}/publish`,
        {},
        activity.revision,
      ),
    )
    .then((activity) => {
      context.activity = activity;
      return rest<JoinCode>(
        context.teacher,
        'POST',
        `/classes/${context.classroom.id}/join-codes`,
        {},
        context.classroom.revision,
      );
    })
    .then((joinCode) =>
      rest(context.student, 'POST', '/class-enrollments', {
        code: joinCode.code,
      }),
    )
    .then(() => cy.wrap(context, { log: false }));
}
function path(context: Setup) {
  return `/actividades/${context.activity.id}/ejercicios/${context.activity.exercises[0]!.id}`;
}
function endpoint(context: Setup) {
  return `/api/v1/activities/${context.activity.id}/exercises/${context.activity.exercises[0]!.id}/attempts`;
}
function visitAs(
  session: Session,
  url: string,
  beforeLoad?: (window: Cypress.AUTWindow) => void,
) {
  return cy.visit(url, {
    onBeforeLoad(window) {
      window.localStorage.setItem(
        'alunza.auth.127.0.0.1:18421',
        JSON.stringify(session),
      );
      beforeLoad?.(window);
    },
  });
}
function writeCode(code: string) {
  // Focus first: entering the browser can trigger access revalidation. Wait for
  // its readonly guard before clearing, then query the controlled input again.
  cy.get('[data-cy="student-code"]')
    .should(($editor) => expect($editor).not.to.have.attr('readonly'))
    .click();
  cy.get('[data-cy="student-code"]')
    .should(($editor) => expect($editor).not.to.have.attr('readonly'))
    .clear();
  cy.get('[data-cy="student-code"]')
    .should('have.value', '')
    .type(code, { parseSpecialCharSequences: false, delay: 0 });
  cy.get('[data-cy="student-code"]').should('have.value', code);
}

function pressEnterInChrome() {
  // Cypress 16's native Enter omits the character event; its type('{enter}')
  // emits a non-bubbling click, which cannot reach React's delegated listener.
  // Supply the complete native CDP keystroke in this Chrome-only lab harness.
  // https://chromedevtools.github.io/devtools-protocol/tot/Input/#method-dispatchKeyEvent
  cy.then(() =>
    Cypress.automation('remote:debugger:protocol', {
      command: 'Input.dispatchKeyEvent',
      params: {
        type: 'keyDown',
        key: 'Enter',
        code: 'Enter',
        text: '\r',
        unmodifiedText: '\r',
        windowsVirtualKeyCode: 13,
        nativeVirtualKeyCode: 13,
      },
    }),
  );
  cy.then(() =>
    Cypress.automation('remote:debugger:protocol', {
      command: 'Input.dispatchKeyEvent',
      params: {
        type: 'keyUp',
        key: 'Enter',
        code: 'Enter',
        windowsVirtualKeyCode: 13,
        nativeVirtualKeyCode: 13,
      },
    }),
  );
}

function renewSession() {
  // Expire only the SDK's local scheduling hint. The unmodified refresh token
  // is exchanged by the real browser Auth client against the real service.
  cy.intercept('POST', '**/auth/v1/token?grant_type=refresh_token').as(
    'tokenRefresh',
  );
  cy.intercept('GET', '**/api/v1/me', (request) =>
    request.continue((response) => {
      response.setDelay(1000);
    }),
  ).as('renewedIdentity');
  cy.window({ log: false }).then((window) => {
    expect(window.document.visibilityState).to.equal('visible');
    const storageKey = 'alunza.auth.127.0.0.1:18421';
    const session = JSON.parse(window.localStorage.getItem(storageKey)!);
    window.localStorage.setItem(
      storageKey,
      JSON.stringify({ ...session, expires_at: 0 }),
    );
    window.dispatchEvent(new window.Event('visibilitychange'));
  });
  cy.wait('@tokenRefresh', { log: false })
    .its('response.statusCode', { log: false })
    .should('equal', 200);
  cy.get('[data-cy="student-code"]').should('not.be.visible');
  cy.wait('@renewedIdentity', { log: false })
    .its('response.statusCode', { log: false })
    .should('equal', 200);
  cy.get('[data-cy="student-code"]')
    .should('be.visible')
    .and('not.have.attr', 'readonly');
}

function submitCode() {
  cy.get('[data-cy="submit-code"]').should('be.enabled').click();
  cy.get('[role="dialog"]').should(
    'contain.text',
    'Confirmar envío de intento',
  );
  cy.get('[data-cy="confirm-submit"]').should('be.enabled').click();
}

describe('IMP-03 · Envíos persistentes con API y Docker reales', () => {
  let releaseDelayedResponse: (() => void) | undefined;
  beforeEach(function () {
    const caseNumber = Number(
      this.currentTest?.title.match(/^IMP03-(\d+)/)?.[1],
    );
    // Stable per-case mapping, also when a single case runs in isolation.
    // Each demo student receives at most four admissions across this suite.
    return setup((caseNumber - 6) % 3).as('submission');
  });
  afterEach(() => {
    // Always release a real response retained by a test, even after an assertion
    // fails, so the request cannot hold the next scenario open.
    releaseDelayedResponse?.();
    releaseDelayedResponse = undefined;
  });

  it('IMP03-06 · HU010 · Cancelar y luego confirmar con teclado → no envía al cancelar y guarda el código capturado con ocultas protegidas', () => {
    cy.get<Setup>('@submission').then((context) => {
      let posts = 0;
      cy.intercept('POST', `**${endpoint(context)}`, (request) => {
        posts++;
        request.continue((response) => {
          expect(response.statusCode, 'admisión real confirmada').to.equal(201);
          return new Promise<void>((resolve) => {
            releaseDelayedResponse = resolve;
          });
        });
      }).as('submit');
      visitAs(context.student, path(context));
      // Passes the visible case and fails the real hidden case.
      const original =
        'module.exports.solve = () => { console.log("<b>salida visible</b>"); return 5; };';
      writeCode(original);
      cy.get('[data-cy="submit-code"]').click();
      cy.get('[data-cy="cancel-submit"]').click();
      cy.get('[role="dialog"]').should('not.exist');
      cy.get('[data-cy="student-code"]').should('have.value', original);
      cy.then(() => expect(posts, 'Cancelar no solicita admisión').to.equal(0));
      cy.get('[data-cy="submit-code"]').click();
      cy.get('[data-cy="confirm-submit"]').focus();
      pressEnterInChrome();
      cy.get('[data-cy="pending-attempt"]').should(
        'contain.text',
        'Envío 1 en curso',
      );
      writeCode('// edición posterior al envío');
      cy.wrap(null, { timeout: 45_000, log: false }).should(() => {
        expect(
          releaseDelayedResponse,
          'respuesta real lista para entregar',
        ).to.be.a('function');
      });
      cy.then(() => {
        releaseDelayedResponse!();
        releaseDelayedResponse = undefined;
      });
      cy.wait('@submit', { responseTimeout: 45_000 }).then(
        ({ request, response }) => {
          expect(response!.statusCode).to.equal(201);
          expect(request.body.code).to.equal(original);
          expect(response!.body.data.code).to.equal(original);
          expect(response!.body.data.technicalResult.diagnosisCode).to.equal(
            'FAILED_TEST',
          );
          expect(response!.body.data.technicalResult.visiblePassed).to.equal(1);
          expect(
            response!.body.data.technicalResult.hiddenChecksPassed,
          ).to.equal(false);
          expect(
            response!.body.data.technicalResult.allRequiredPassed,
          ).to.equal(false);
          expect(JSON.stringify(response!.body)).not.to.contain(
            'hidden-submit-sentinel',
          );
          expect(JSON.stringify(response!.body)).not.to.contain('98761');
        },
      );
      cy.get('[data-cy="saved-snapshot"]').should(
        'contain.text',
        'cambios posteriores',
      );
      cy.get('[data-cy="attempt-diagnosis"]').should(
        'contain.text',
        'FAILED_TEST',
      );
      cy.get('[data-cy="attempt-result"] b').should('not.exist');
      cy.get('[data-cy="activity-progress"]').should(
        'contain.text',
        'completados: 0/1',
      );
      cy.reload();
      cy.get('[data-cy="student-code"]').should(
        'have.value',
        '// edición posterior al envío',
      );
      cy.get('[data-cy="attempt-history-row"]').should('have.length', 1);
      cy.get('[data-cy="show-attempt"]').click();
      cy.get('[data-cy="attempt-detail"]').should(
        'contain.text',
        'Intento #1 guardado',
      );
      cy.get('[data-cy="attempt-detail"] summary').click();
      cy.get('[data-cy="attempt-source"]').should('have.text', original);
    });
  });

  it('IMP03-07 · HU011/HU014/RF007 · Copiar y reintentar → conserva intentos, compara pruebas visibles y mantiene un éxito ante un fallo posterior', () => {
    cy.get<Setup>('@submission').then((context) => {
      let firstId: string;
      const keys = new Set<string>();
      cy.intercept('POST', `**${endpoint(context)}`).as('submit');
      visitAs(context.student, path(context));
      cy.get('[data-cy="activity-progress"]').should(
        'contain.text',
        'Sin intentos',
      );
      writeCode('module.exports.solve = () => 0;');
      submitCode();
      cy.wait('@submit', { responseTimeout: 45_000 }).then(
        ({ request, response }) => {
          firstId = response!.body.data.attemptId;
          expect(response!.statusCode).to.equal(201);
          keys.add(String(request.headers['idempotency-key']));
        },
      );
      cy.get('[data-cy="attempt-history-row"]').should('have.length', 1);
      cy.get('[data-cy="show-attempt"]').click();
      writeCode('// borrador que debe conservarse si cancelo');
      cy.get('[data-cy="copy-attempt"]').click();
      cy.get('[role="dialog"]').should(
        'contain.text',
        'reemplazará el borrador',
      );
      cy.get('[role="dialog"]').contains('button', 'Cancelar').click();
      cy.get('[data-cy="student-code"]').should(
        'have.value',
        '// borrador que debe conservarse si cancelo',
      );
      cy.get('[data-cy="copy-attempt"]').click();
      cy.get('[data-cy="confirm-copy"]').click();
      cy.get('[data-cy="student-code"]').should(
        'have.value',
        'module.exports.solve = () => 0;',
      );
      writeCode(correct);
      submitCode();
      cy.wait('@submit', { responseTimeout: 45_000 }).then(
        ({ request, response }) => {
          expect(request.body.previousAttemptId).to.equal(firstId);
          expect(response!.statusCode).to.equal(201);
          expect(response!.body.data.attemptId).not.to.equal(firstId);
          expect(
            response!.body.data.technicalResult.allRequiredPassed,
          ).to.equal(true);
          expect(keys.has(String(request.headers['idempotency-key']))).to.equal(
            false,
          );
          keys.add(String(request.headers['idempotency-key']));
        },
      );
      cy.get('[data-cy="attempt-history-row"]').should('have.length', 2);
      cy.get('[data-cy="compare-attempt"]').check();
      cy.get('[data-cy="attempt-comparison"]')
        .should('contain.text', 'Intento #1: 0/1')
        .and('contain.text', 'Intento #2: 1/1')
        .and('contain.text', 'Diferencia: +1');
      writeCode('module.exports.solve = () => 0;');
      submitCode();
      cy.wait('@submit', { responseTimeout: 45_000 }).then(
        ({ request, response }) => {
          expect(response!.statusCode).to.equal(201);
          expect(
            response!.body.data.technicalResult.allRequiredPassed,
          ).to.equal(false);
          expect(keys.has(String(request.headers['idempotency-key']))).to.equal(
            false,
          );
        },
      );
      cy.get('[data-cy="attempt-history-row"]').should('have.length', 3);
      cy.get('[data-cy="activity-progress"]').should(
        'contain.text',
        'completados: 1/1',
      );
      cy.visit(`/actividades/${context.activity.id}`);
      cy.get('[data-cy="activity-progress"]').should(
        'contain.text',
        'completados: 1/1',
      );
      cy.visit(`/clases/${context.classroom.id}`);
      cy.get('[data-cy="activity-card"]').should(
        'contain.text',
        'completados: 1/1',
      );
      // Fail only the progress transport once. Identity/content stay real, and
      // retry must obtain the committed aggregate from the API without stubs.
      const progressEndpoint = `**/api/v1/activities/${context.activity.id}/progress`;
      cy.intercept(
        { method: 'GET', url: progressEndpoint, times: 1 },
        { forceNetworkError: true },
      ).as('progressUnavailable');
      cy.visit(`/actividades/${context.activity.id}`);
      cy.wait('@progressUnavailable');
      cy.get('[data-cy="activity-progress"]').within(() => {
        cy.get('[role="alert"]').should(
          'contain.text',
          'Consulta no disponible',
        );
        cy.root()
          .should('not.contain.text', 'completados:')
          .and('not.contain.text', 'Sin intentos')
          .and('not.contain.text', 'Sin ejercicios requeridos');
      });
      cy.intercept('GET', progressEndpoint).as('progressRecovered');
      cy.get('[data-cy="activity-progress"]')
        .contains('button', 'Reintentar consulta')
        .click();
      cy.wait('@progressRecovered').then(({ response }) => {
        expect(response!.statusCode).to.equal(200);
        expect(response!.body.data).to.include({
          completed: 1,
          required: 1,
          ratio: 1,
          evidenceState: 'HAS_EVIDENCE',
        });
      });
      cy.get('[data-cy="activity-progress"]').should(
        'contain.text',
        'completados: 1/1',
      );
      cy.get('[data-cy="activity-progress"] [role="alert"]').should(
        'not.exist',
      );
    });
  });

  it('IMP03-08 · HU010/DEC002 · Perder respuesta, renovar sesión y cerrar → recupera el mismo intento sin reemplazar el borrador aun sin storage', () => {
    cy.get<Setup>('@submission').then((context) => {
      cy.intercept('POST', `**${endpoint(context)}`).as('initialSubmit');
      let loseResponse: (() => void) | undefined;
      let requestSignal: AbortSignal | null | undefined;
      const observed: {
        key: string | null;
        body: string;
        attemptId: string;
      }[] = [];
      visitAs(context.student, path(context), (window) => {
        const original = window.fetch.bind(window);
        const setItem = window.Storage.prototype.setItem;
        window.Storage.prototype.setItem = function (key, value) {
          if (
            key.startsWith('alunza.exercise-draft.v1:') ||
            key.startsWith('alunza.pending-attempts.v1:')
          )
            throw new window.DOMException('Storage unavailable');
          return setItem.call(this, key, value);
        };
        // The real transaction finishes; only delivery to the browser is lost.
        window.fetch = (input, init) =>
          original(input, init).then(async (response) => {
            if (
              String(input).endsWith(endpoint(context)) &&
              init?.method === 'POST' &&
              response.status === 201
            ) {
              const data = (await response.clone().json()).data;
              observed.push({
                key: new Headers(init.headers).get('Idempotency-Key'),
                body: String(init.body),
                attemptId: data.attemptId,
              });
              if (observed.length === 1) {
                requestSignal = init.signal;
                return new Promise<Response>((_resolve, reject) => {
                  loseResponse = () =>
                    reject(new TypeError('Lost committed response'));
                });
              }
            }
            return response;
          });
      });
      writeCode(correct);
      submitCode();
      cy.wait('@initialSubmit', { responseTimeout: 45_000 })
        .its('response.statusCode')
        .should('equal', 201);
      cy.wrap(null, { timeout: 45_000, log: false }).should(() =>
        expect(loseResponse).to.be.a('function'),
      );
      writeCode('// borrador posterior protegido en memoria');
      cy.get('#draft-status').should('contain.text', 'No se pudo guardar');
      renewSession();
      cy.get('[data-cy="pending-attempt"]').should('contain.text', 'en curso');
      cy.then(() => {
        expect(requestSignal?.aborted).to.equal(false);
        loseResponse!();
      });
      cy.get('[data-cy="recover-submit"]').should('be.enabled');
      rest<Activity>(
        context.teacher,
        'POST',
        `/activities/${context.activity.id}/close`,
        {},
        context.activity.revision,
      );
      cy.contains('button', 'Actualizar disponibilidad').click();
      cy.get('[data-cy="student-code"]').should('have.attr', 'readonly');
      cy.get('[data-cy="submit-code"]').should('be.disabled');
      cy.get('[data-cy="recover-submit"]').should('be.enabled').click();
      cy.get('[data-cy="attempt-diagnosis"]', { timeout: 45_000 }).should(
        'contain.text',
        'SUCCESS',
      );
      cy.get('[data-cy="student-code"]').should(
        'have.value',
        '// borrador posterior protegido en memoria',
      );
      cy.get('[data-cy="attempt-history-row"]').should('have.length', 1);
      cy.get('[data-cy="show-attempt"]').click();
      cy.get('[data-cy="copy-attempt"]').should('be.disabled');
      cy.then(() => {
        expect(observed).to.have.length(2);
        expect(observed[1]).to.deep.equal(observed[0]);
      });
    });
  });

  it('IMP03-09 · HU014-E4 · Confirmar dos envíos intencionales → conserva snapshots separados y orden estable pese a respuestas invertidas', () => {
    cy.get<Setup>('@submission').then((context) => {
      cy.intercept('POST', `**${endpoint(context)}`).as('initialSubmit');
      let releaseFirst: (() => void) | undefined;
      const submissions: {
        key: string | null;
        attemptId: string;
        code: string;
      }[] = [];
      visitAs(context.student, path(context), (window) => {
        const original = window.fetch.bind(window);
        window.fetch = (input, init) =>
          original(input, init).then(async (response) => {
            if (
              String(input).endsWith(endpoint(context)) &&
              init?.method === 'POST' &&
              response.status === 201
            ) {
              const attempt = (await response.clone().json()).data;
              submissions.push({
                key: new Headers(init.headers).get('Idempotency-Key'),
                attemptId: attempt.attemptId,
                code: attempt.code,
              });
              if (submissions.length === 1)
                return new Promise<Response>((resolve) => {
                  releaseFirst = () => resolve(response);
                });
            }
            return response;
          });
      });
      writeCode('module.exports.solve = () => 0;');
      submitCode();
      cy.wait('@initialSubmit', { responseTimeout: 45_000 })
        .its('response.statusCode')
        .should('equal', 201);
      cy.wrap(null, { timeout: 45_000 }).should(() =>
        expect(releaseFirst).to.be.a('function'),
      );
      writeCode(correct);
      cy.get('[data-cy="submit-code"]').should('be.enabled').click();
      cy.get('[role="dialog"]').should(
        'contain.text',
        'creará un intento distinto',
      );
      cy.get('[data-cy="confirm-submit"]').click();
      cy.get('[data-cy="attempt-diagnosis"]', { timeout: 45_000 }).should(
        'contain.text',
        'SUCCESS',
      );
      cy.then(() => releaseFirst!());
      cy.get('[data-cy="pending-attempt"]').should('not.exist');
      cy.get('[data-cy="attempt-history-row"]')
        .should('have.length', 2)
        .first()
        .should('contain.text', 'Intento #2');
      cy.get('[data-cy="attempt-diagnosis"]').should('contain.text', 'SUCCESS');
      cy.then(() => {
        expect(submissions).to.have.length(2);
        expect(submissions[0]!.key).not.to.equal(submissions[1]!.key);
        expect(submissions[0]!.attemptId).not.to.equal(
          submissions[1]!.attemptId,
        );
        expect(submissions[0]!.code).to.equal(
          'module.exports.solve = () => 0;',
        );
        expect(submissions[1]!.code).to.equal(correct);
      });
    });
  });

  it('IMP03-10 · HU010/SEG01 · Cambiar de cuenta con respuesta tardía → no muestra código ni resultados a la otra cuenta y recupera al volver', () => {
    cy.get<Setup>('@submission').then((context) => {
      cy.intercept('POST', `**${endpoint(context)}`).as('initialSubmit');
      let releaseResponse: (() => void) | undefined;
      let requestSignal: AbortSignal | null | undefined;
      const source =
        'module.exports.solve = (a,b) => { console.log("resultado privado de SUBMIT"); return a+b; };';
      visitAs(context.student, path(context), (window) => {
        const original = window.fetch.bind(window);
        window.fetch = (input, init) =>
          original(input, init).then((response) => {
            if (
              String(input).endsWith(endpoint(context)) &&
              init?.method === 'POST' &&
              response.status === 201
            ) {
              requestSignal = init.signal;
              return new Promise<Response>((resolve) => {
                releaseResponse = () => resolve(response);
              });
            }
            return response;
          });
      });
      writeCode(source);
      submitCode();
      cy.wait('@initialSubmit', { responseTimeout: 45_000 })
        .its('response.statusCode')
        .should('equal', 201);
      cy.wrap(null, { timeout: 45_000 }).should(() =>
        expect(releaseResponse).to.be.a('function'),
      );
      cy.contains('button', /^Cerrar sesión$/).click();
      cy.location('pathname').should('equal', '/acceso');
      cy.wrap(null).should(() => expect(requestSignal?.aborted).to.equal(true));
      const admin = identityFixture.users.find(
        (user) =>
          user.organizationId === organizationId && user.role === 'ADMIN',
      )!;
      cy.get('#email').type(admin.email, { log: false });
      cy.env(['fixturePassword'], { log: false }).then(({ fixturePassword }) =>
        cy.get('#password').type(String(fixturePassword), {
          log: false,
          parseSpecialCharSequences: false,
        }),
      );
      cy.contains('button', /^Iniciar sesión$/).click();
      cy.location('pathname').should('equal', '/inicio');
      cy.then(() => releaseResponse!());
      cy.get('[data-cy="attempt-result"]').should('not.exist');
      cy.get('[data-cy="recover-submit"]').should('not.exist');
      cy.contains('resultado privado de SUBMIT').should('not.exist');
      cy.visit(path(context));
      cy.get('[role="alert"]').should('be.visible');
      cy.get('[data-cy="student-code"]').should('not.exist');
      cy.get('[data-cy="attempt-history"]').should('not.exist');
      cy.task<Session>('identity:login', context.studentFixture, {
        log: false,
      }).then((session) => visitAs(session, path(context)));
      cy.get('[data-cy="student-code"]').should('have.value', source);
      cy.get('[data-cy="recover-submit"]').should('be.enabled').click();
      cy.get('[data-cy="attempt-diagnosis"]', { timeout: 45_000 }).should(
        'contain.text',
        'SUCCESS',
      );
      cy.get('[data-cy="attempt-history-row"]').should('have.length', 1);
    });
  });

  it('IMP03-11 · HU010/HU011 · Reiniciar API y recargar tras una respuesta perdida → recupera la clave original y consulta un único intento guardado', () => {
    cy.get<Setup>('@submission').then((context) => {
      cy.intercept('POST', `**${endpoint(context)}`).as('initialSubmit');
      let originalKey: string | null;
      let originalId: string;
      visitAs(context.student, path(context), (window) => {
        const original = window.fetch.bind(window);
        window.fetch = (input, init) =>
          original(input, init).then(async (response) => {
            if (
              String(input).endsWith(endpoint(context)) &&
              init?.method === 'POST' &&
              response.status === 201
            ) {
              originalKey = new Headers(init.headers).get('Idempotency-Key');
              originalId = (await response.clone().json()).data.attemptId;
              throw new TypeError('Response lost after commit');
            }
            return response;
          });
      });
      writeCode(correct);
      submitCode();
      cy.wait('@initialSubmit', { responseTimeout: 45_000 })
        .its('response.statusCode')
        .should('equal', 201);
      cy.get('[data-cy="recover-submit"]', { timeout: 45_000 }).should(
        'be.enabled',
      );
      cy.then(() => {
        expect(
          originalId,
          'intento confirmado por la API real antes del reinicio',
        )
          .to.be.a('string')
          .and.not.equal('');
        expect(originalKey, 'clave original conservada')
          .to.be.a('string')
          .and.not.equal('');
      });
      // Restart the real Nest process after commit; the replay must come from
      // durable data, independently of both server and browser memory.
      cy.task('foundation:apiStop', null, { log: false });
      cy.task('foundation:apiStart', null, { log: false });
      cy.reload();
      cy.intercept('POST', `**${endpoint(context)}`).as('recovery');
      cy.get('[data-cy="recover-submit"]').should('be.enabled').click();
      cy.wait('@recovery', { responseTimeout: 45_000 }).then(
        ({ request, response }) => {
          expect(request.headers['idempotency-key']).to.equal(originalKey);
          expect(response!.body.data.attemptId).to.equal(originalId);
          expect(response!.body.data.code).to.equal(correct);
        },
      );
      cy.get('[data-cy="attempt-history-row"]').should('have.length', 1);
      cy.get('[data-cy="recover-submit"]').should('not.exist');
      cy.reload();
      cy.get('[data-cy="recover-submit"]').should('not.exist');
      cy.get('[data-cy="attempt-history-row"]').should('have.length', 1);
    });
  });
});
