// Generated by Cypress Author on 2026-09-10 for IMP-00.05.

beforeEach(() => {
  // Documented pass-through logging suppression. No response body/status is stubbed.
  cy.intercept({ resourceType: /xhr|fetch/ }, { log: false });
  cy.task('foundation:apiStart', null, { log: false });
});

afterEach(() => {
  // A failed assertion in an outage test must not leave later tests without an API.
  cy.task('foundation:apiStart', null, { log: false });
});
