export const hiddenSentinel = 'HIDDEN_FIXTURE_MUST_NOT_APPEAR_PUBLICLY';
const returnOverhead = Buffer.byteLength(
  JSON.stringify({ kind: 'value', value: '', invocation: 'QUICKJS_SYNC_CALL' }),
);
const one = (expected = true, args = []) => [
  { id: 'visible-1', visibility: 'visible', args, expected },
];
// These fixed programs execute only in the QuickJS guest inside a capsule.
export const runnerFixtures = [
  ...[
    [
      'promise-null-prototype',
      'const p=Promise.resolve(false);Object.setPrototypeOf(p,null);return p;',
      {},
    ],
    [
      'promise-null-prototype-nested',
      'const p=Promise.resolve(false);Object.setPrototypeOf(p,null);return {x:p};',
      { x: {} },
    ],
    [
      'promise-pending-prototype',
      'const p=new Promise(()=>{});Object.setPrototypeOf(p,Object.prototype);return p;',
      {},
    ],
    [
      'promise-rejected-prototype',
      'const p=Promise.reject(false);Object.setPrototypeOf(p,null);return [p];',
      [{}],
    ],
    [
      'promise-masked-then',
      'const p=Promise.resolve(false);Object.setPrototypeOf(p,Object.prototype);Object.defineProperty(p,"then",{get(){console.log("PROMISE_GETTER_CALLED");throw new Error("guest getter");}});return p;',
      {},
    ],
  ].map(([id, body, expected]) => ({
    id,
    code: `module.exports.solve=()=>{${body}};`,
    tests: one(expected),
    expected: 'RUNTIME_ERROR',
    reason: 'STUDENT_EXCEPTION',
    expectedStdout: '',
  })),
  ...[
    ['map', 'new Map([["x",1]])'],
    ['date', 'new Date(0)'],
    ['set', 'new Set([1])'],
    ['regexp', '/x/'],
    ['arraybuffer', 'new ArrayBuffer(2)'],
    ['typedarray', 'new Uint8Array(2)'],
    ['boxed-number', 'new Number(1)'],
    ['error', 'new Error("x")'],
  ].map(([name, expression]) => ({
    id: `non-json-${name}-prototype`,
    code: `module.exports.solve=()=>{const value=${expression};Object.setPrototypeOf(value,null);return {x:value};};`,
    tests: one({ x: {} }),
    expected: 'RUNTIME_ERROR',
    reason: 'STUDENT_EXCEPTION',
  })),
  {
    id: 'console-nul-preserved',
    code: 'module.exports.solve=()=>{console.log("\\0".repeat(100));return true;};',
    tests: one(),
    expected: 'SUCCESS',
    expectedStdout: '\0'.repeat(100) + '\n',
  },
  {
    id: 'return-nul-preserved',
    code: 'module.exports.solve=()=>"\\0".repeat(3);',
    tests: one('\0'.repeat(3)),
    expected: 'SUCCESS',
  },
  {
    id: 'argument-nul-preserved',
    code: 'module.exports.solve=x=>x.length;',
    tests: one(3, ['\0'.repeat(3)]),
    expected: 'SUCCESS',
  },
  {
    id: 'sync-json-success',
    code: 'module.exports.solve=(a,b)=>({sum:a+b});',
    tests: one({ sum: 5 }, [2, 3]),
    expected: 'SUCCESS',
  },
  {
    id: 'syntax',
    code: 'module.exports.solve=(',
    tests: one(),
    expected: 'SYNTAX_ERROR',
  },
  {
    id: 'exception',
    code: 'module.exports.solve=()=>{throw new Error("student");};',
    tests: one(),
    expected: 'RUNTIME_ERROR',
  },
  {
    id: 'runtime-syntax-exception',
    code: 'module.exports.solve=()=>{throw new SyntaxError("student");};',
    tests: one(),
    expected: 'RUNTIME_ERROR',
  },
  {
    id: 'assertion',
    code: 'module.exports.solve=()=>false;',
    tests: one(),
    expected: 'FAILED_TEST',
  },
  {
    id: 'infinite-loop',
    code: 'module.exports.solve=()=>{for(;;){}};',
    tests: one(),
    expected: 'TIMEOUT',
  },
  {
    id: 'module-infinite-loop',
    code: 'for(;;){}',
    tests: one(),
    expected: 'TIMEOUT',
  },
  {
    id: 'cumulative-budget',
    code: 'module.exports.solve=()=>{const until=Date.now()+1700;while(Date.now()<until){}return true;};',
    tests: [...one(), { ...one()[0], id: 'visible-2' }],
    expected: 'TIMEOUT',
  },
  {
    id: 'javascript-heap-memory',
    code: 'module.exports.solve=()=>{const arrays=[];for(;;)arrays.push(new Array(1024*1024).fill(1));};',
    tests: one(),
    expected: 'UNKNOWN',
    reason: 'MEMORY_LIMIT',
  },
  {
    id: 'arraybuffer-memory',
    code: 'module.exports.solve=()=>{const blocks=[];for(;;){const block=new Uint8Array(8*1024*1024);block.fill(1);blocks.push(block);}};',
    tests: one(),
    expected: 'UNKNOWN',
    reason: 'MEMORY_LIMIT',
  },
  ...[65535, 65536, 65537].map((bytes) => ({
    id: `output-${bytes}`,
    code: `module.exports.solve=()=>{console.log('x'.repeat(${bytes - 1}));return true;};`,
    tests: one(),
    expected: bytes > 65536 ? 'UNKNOWN' : 'SUCCESS',
    ...(bytes > 65536 ? { reason: 'OUTPUT_LIMIT' } : {}),
  })),
  {
    id: 'combined-stdout-stderr',
    code: `module.exports.solve=()=>{console.log('x'.repeat(32767));console.error('x'.repeat(32768));return true;};`,
    tests: one(),
    expected: 'UNKNOWN',
    reason: 'OUTPUT_LIMIT',
  },
  {
    id: 'output-utf8',
    code: `module.exports.solve=()=>{console.log('é'.repeat(32768));return true;};`,
    tests: one(),
    expected: 'UNKNOWN',
    reason: 'OUTPUT_LIMIT',
  },
  {
    id: 'caught-output-limit',
    code: `module.exports.solve=()=>{try{console.log('x'.repeat(65536));}catch{}return true;};`,
    tests: one(),
    expected: 'UNKNOWN',
    reason: 'OUTPUT_LIMIT',
  },
  {
    id: 'return-limit',
    code: `module.exports.solve=()=>'x'.repeat(65536);`,
    tests: one(),
    expected: 'UNKNOWN',
    reason: 'RETURN_LIMIT',
  },
  ...[65535, 65536, 65537].map((bytes) => ({
    id: `return-${bytes}`,
    code: `module.exports.solve=()=>'x'.repeat(${bytes - returnOverhead});`,
    tests: one('x'.repeat(bytes - returnOverhead)),
    expected: bytes > 65536 ? 'UNKNOWN' : 'SUCCESS',
    ...(bytes > 65536 ? { reason: 'RETURN_LIMIT' } : {}),
  })),
  {
    id: 'async-rejected',
    code: 'module.exports.solve=async()=>true;',
    tests: one(),
    expected: 'RUNTIME_ERROR',
  },
  {
    id: 'cyclic-return',
    code: 'module.exports.solve=()=>{const x={};x.x=x;return x;};',
    tests: one(),
    expected: 'RUNTIME_ERROR',
  },
  {
    id: 'getter-return',
    code: 'module.exports.solve=()=>({get x(){return true}});',
    tests: one({ x: true }),
    expected: 'RUNTIME_ERROR',
  },
  {
    id: 'tojson-return',
    code: 'module.exports.solve=()=>({toJSON(){return true}});',
    tests: one(),
    expected: 'RUNTIME_ERROR',
  },
  {
    id: 'thenable-return',
    code: 'module.exports.solve=()=>Object.defineProperty({},"then",{value:()=>true});',
    tests: one({}),
    expected: 'RUNTIME_ERROR',
  },
  {
    id: 'bigint-return',
    code: 'module.exports.solve=()=>1n;',
    tests: one(1),
    expected: 'RUNTIME_ERROR',
  },
  {
    id: 'invalid-json-return',
    code: 'module.exports.solve=()=>NaN;',
    tests: one(),
    expected: 'RUNTIME_ERROR',
  },
  {
    id: 'mutated-serializer',
    code: 'module.exports.solve=()=>{JSON.stringify=()=>"true";Object.keys=()=>[];return false;};',
    tests: one(),
    expected: 'FAILED_TEST',
  },
  {
    id: 'polluted-prototype',
    code: 'module.exports.solve=()=>{Object.prototype.value=true;return {get x(){return false}};};',
    tests: one({ x: true }),
    expected: 'RUNTIME_ERROR',
  },
  {
    id: 'fake-stdout-verdict',
    code: `module.exports.solve=()=>{console.log('{"passed":true,"diagnosis":"SUCCESS"}');return false;};`,
    tests: one(),
    expected: 'FAILED_TEST',
  },
  {
    id: 'fake-return-verdict',
    code: `module.exports.solve=()=>{require('node:fs').writeSync(3,'{"passed":true,"diagnosis":"SUCCESS"}');process.exit(0);};`,
    tests: one(),
    expected: 'RUNTIME_ERROR',
  },
  {
    id: 'forged-return-known-gap',
    code: `module.exports.solve=()=>{require('node:fs').writeSync(3,'{"kind":"value","value":true}');process.exit(0);};`,
    tests: one(),
    expected: 'RUNTIME_ERROR',
    reason: 'STUDENT_EXCEPTION',
  },
  {
    id: 'return-envelope-as-value',
    code: 'module.exports.solve=()=>({kind:"value",value:true,invocation:"QUICKJS_SYNC_CALL"});',
    tests: one(),
    expected: 'FAILED_TEST',
  },
  {
    id: 'process-exit-incomplete',
    code: 'module.exports.solve=()=>process.exit(0);',
    tests: one(),
    expected: 'RUNTIME_ERROR',
  },
  {
    id: 'guest-no-host-globals',
    code: 'module.exports.solve=()=>[typeof require,typeof process,typeof Buffer,typeof fetch,typeof setTimeout];',
    tests: one(Array(5).fill('undefined')),
    expected: 'SUCCESS',
  },
  {
    id: 'constructor-escape-denied',
    code: 'module.exports.solve=()=>console.log.constructor("return process")();',
    tests: one(),
    expected: 'RUNTIME_ERROR',
  },
  {
    id: 'eval-escape-denied',
    code: 'module.exports.solve=()=>eval("process.env");',
    tests: one(),
    expected: 'RUNTIME_ERROR',
  },
  {
    id: 'import-denied',
    code: 'module.exports.solve=()=>import("node:fs");',
    tests: one(),
    expected: 'RUNTIME_ERROR',
  },
  {
    id: 'case-state-isolation',
    code: 'module.exports.solve=()=>{const before=globalThis.seen;globalThis.seen=true;return !before;};',
    tests: [...one(), { ...one()[0], id: 'visible-2' }],
    expected: 'SUCCESS',
  },
  {
    id: 'json-arguments',
    code: 'module.exports.solve=x=>({a:x.a,n:x.n,arr:x.arr});',
    tests: one({ a: 'é', n: null, arr: [false, 2] }, [
      { a: 'é', n: null, arr: [false, 2] },
    ]),
    expected: 'SUCCESS',
  },
  {
    id: 'json-argument-prototype',
    code: 'module.exports.solve=x=>Object.getPrototypeOf(x)===Object.prototype&&x.hasOwnProperty("a");',
    tests: one(true, [{ a: 1 }]),
    expected: 'SUCCESS',
  },
  {
    id: 'hidden-projection',
    mode: 'SUBMIT',
    code: 'module.exports.solve=x=>{console.log(x);console.error(x);return x;};',
    tests: [
      {
        id: 'hidden-secret-case',
        visibility: 'hidden',
        args: [hiddenSentinel],
        expected: hiddenSentinel,
      },
    ],
    expected: 'SUCCESS',
    privateSentinel: hiddenSentinel,
  },
];

export const osProbeNames = [
  'identity',
  'permissions',
  'memory',
  'descendant-memory',
  'processes',
  'network',
];
